// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/common.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminFormControl int32

const (
	AdminFormControl_ADMIN_FORM_CONTROL_UNSPECIFIED  AdminFormControl = 0
	AdminFormControl_ADMIN_FORM_CONTROL_TEXT         AdminFormControl = 1
	AdminFormControl_ADMIN_FORM_CONTROL_TEXTAREA     AdminFormControl = 2
	AdminFormControl_ADMIN_FORM_CONTROL_PASSWORD     AdminFormControl = 3
	AdminFormControl_ADMIN_FORM_CONTROL_NUMBER       AdminFormControl = 4
	AdminFormControl_ADMIN_FORM_CONTROL_SWITCH       AdminFormControl = 5
	AdminFormControl_ADMIN_FORM_CONTROL_SELECT       AdminFormControl = 6
	AdminFormControl_ADMIN_FORM_CONTROL_MULTI_SELECT AdminFormControl = 7 // array-of-values (e.g. tags)
)

// Enum value maps for AdminFormControl.
var (
	AdminFormControl_name = map[int32]string{
		0: "ADMIN_FORM_CONTROL_UNSPECIFIED",
		1: "ADMIN_FORM_CONTROL_TEXT",
		2: "ADMIN_FORM_CONTROL_TEXTAREA",
		3: "ADMIN_FORM_CONTROL_PASSWORD",
		4: "ADMIN_FORM_CONTROL_NUMBER",
		5: "ADMIN_FORM_CONTROL_SWITCH",
		6: "ADMIN_FORM_CONTROL_SELECT",
		7: "ADMIN_FORM_CONTROL_MULTI_SELECT",
	}
	AdminFormControl_value = map[string]int32{
		"ADMIN_FORM_CONTROL_UNSPECIFIED":  0,
		"ADMIN_FORM_CONTROL_TEXT":         1,
		"ADMIN_FORM_CONTROL_TEXTAREA":     2,
		"ADMIN_FORM_CONTROL_PASSWORD":     3,
		"ADMIN_FORM_CONTROL_NUMBER":       4,
		"ADMIN_FORM_CONTROL_SWITCH":       5,
		"ADMIN_FORM_CONTROL_SELECT":       6,
		"ADMIN_FORM_CONTROL_MULTI_SELECT": 7,
	}
)

func (x AdminFormControl) Enum() *AdminFormControl {
	p := new(AdminFormControl)
	*p = x
	return p
}

func (x AdminFormControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminFormControl) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_common_proto_enumTypes[0].Descriptor()
}

func (AdminFormControl) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_common_proto_enumTypes[0]
}

func (x AdminFormControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminFormControl.Descriptor instead.
func (AdminFormControl) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

type SupportedPlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedPlatform) Reset() {
	*x = SupportedPlatform{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedPlatform) ProtoMessage() {}

func (x *SupportedPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedPlatform.ProtoReflect.Descriptor instead.
func (*SupportedPlatform) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SupportedPlatform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SupportedPlatform) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	JsonSchema    string                 `protobuf:"bytes,4,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	AdminForm     *AdminFormDescriptor   `protobuf:"bytes,6,opt,name=admin_form,json=adminForm,proto3" json:"admin_form,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchema) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSchema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConfigSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ConfigSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigSchema) GetAdminForm() *AdminFormDescriptor {
	if x != nil {
		return x.AdminForm
	}
	return nil
}

type AdminFormOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormOption) Reset() {
	*x = AdminFormOption{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormOption) ProtoMessage() {}

func (x *AdminFormOption) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormOption.ProtoReflect.Descriptor instead.
func (*AdminFormOption) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AdminFormOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AdminFormOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminFormOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AdminFormField struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label          string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Control        AdminFormControl       `protobuf:"varint,4,opt,name=control,proto3,enum=silo.plugin.v1.AdminFormControl" json:"control,omitempty"`
	Placeholder    string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Required       bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	Secret         bool                   `protobuf:"varint,7,opt,name=secret,proto3" json:"secret,omitempty"`
	Multiline      bool                   `protobuf:"varint,8,opt,name=multiline,proto3" json:"multiline,omitempty"`
	DefaultValue   *structpb.Value        `protobuf:"bytes,9,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options        []*AdminFormOption     `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Rows           int32                  `protobuf:"varint,11,opt,name=rows,proto3" json:"rows,omitempty"`
	DynamicOptions bool                   `protobuf:"varint,12,opt,name=dynamic_options,json=dynamicOptions,proto3" json:"dynamic_options,omitempty"` // populate options from ListConfigOptions[key]
	ShowWhen       []*AdminFormCondition  `protobuf:"bytes,13,rep,name=show_when,json=showWhen,proto3" json:"show_when,omitempty"`                    // conditional visibility
	Validation     *AdminFormValidation   `protobuf:"bytes,14,opt,name=validation,proto3" json:"validation,omitempty"`                                // per-field constraints
	// exclusive_group_field names another config field whose value defines a
	// group; at most one connection per distinct value of that field may have THIS
	// field truthy. Empty = no exclusivity.
	ExclusiveGroupField string `protobuf:"bytes,15,opt,name=exclusive_group_field,json=exclusiveGroupField,proto3" json:"exclusive_group_field,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminFormField) Reset() {
	*x = AdminFormField{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormField) ProtoMessage() {}

func (x *AdminFormField) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormField.ProtoReflect.Descriptor instead.
func (*AdminFormField) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *AdminFormField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminFormField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminFormField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminFormField) GetControl() AdminFormControl {
	if x != nil {
		return x.Control
	}
	return AdminFormControl_ADMIN_FORM_CONTROL_UNSPECIFIED
}

func (x *AdminFormField) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *AdminFormField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AdminFormField) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *AdminFormField) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

func (x *AdminFormField) GetDefaultValue() *structpb.Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *AdminFormField) GetOptions() []*AdminFormOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AdminFormField) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *AdminFormField) GetDynamicOptions() bool {
	if x != nil {
		return x.DynamicOptions
	}
	return false
}

func (x *AdminFormField) GetShowWhen() []*AdminFormCondition {
	if x != nil {
		return x.ShowWhen
	}
	return nil
}

func (x *AdminFormField) GetValidation() *AdminFormValidation {
	if x != nil {
		return x.Validation
	}
	return nil
}

func (x *AdminFormField) GetExclusiveGroupField() string {
	if x != nil {
		return x.ExclusiveGroupField
	}
	return ""
}

// AdminFormCondition: the owning field/section is shown only when, for every
// listed condition, the named field's stringified value is in `equals`.
type AdminFormCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Equals        []string               `protobuf:"bytes,2,rep,name=equals,proto3" json:"equals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormCondition) Reset() {
	*x = AdminFormCondition{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormCondition) ProtoMessage() {}

func (x *AdminFormCondition) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormCondition.ProtoReflect.Descriptor instead.
func (*AdminFormCondition) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *AdminFormCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AdminFormCondition) GetEquals() []string {
	if x != nil {
		return x.Equals
	}
	return nil
}

// AdminFormValidation: per-field constraints, enforced client-side and
// re-checked server-side. has_min/has_max distinguish "unset" from a real 0.
type AdminFormValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasMin        bool                   `protobuf:"varint,1,opt,name=has_min,json=hasMin,proto3" json:"has_min,omitempty"`
	Min           float64                `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	HasMax        bool                   `protobuf:"varint,3,opt,name=has_max,json=hasMax,proto3" json:"has_max,omitempty"`
	Max           float64                `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	Pattern       string                 `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"` // RE2
	MinLength     int32                  `protobuf:"varint,6,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength     int32                  `protobuf:"varint,7,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormValidation) Reset() {
	*x = AdminFormValidation{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormValidation) ProtoMessage() {}

func (x *AdminFormValidation) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormValidation.ProtoReflect.Descriptor instead.
func (*AdminFormValidation) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *AdminFormValidation) GetHasMin() bool {
	if x != nil {
		return x.HasMin
	}
	return false
}

func (x *AdminFormValidation) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AdminFormValidation) GetHasMax() bool {
	if x != nil {
		return x.HasMax
	}
	return false
}

func (x *AdminFormValidation) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AdminFormValidation) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AdminFormValidation) GetMinLength() int32 {
	if x != nil {
		return x.MinLength
	}
	return 0
}

func (x *AdminFormValidation) GetMaxLength() int32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

// AdminFormSection groups fields (by key) into an ordered, optionally
// collapsible section with its own visibility.
type AdminFormSection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Collapsible      bool                   `protobuf:"varint,4,opt,name=collapsible,proto3" json:"collapsible,omitempty"`
	CollapsedDefault bool                   `protobuf:"varint,5,opt,name=collapsed_default,json=collapsedDefault,proto3" json:"collapsed_default,omitempty"`
	FieldKeys        []string               `protobuf:"bytes,6,rep,name=field_keys,json=fieldKeys,proto3" json:"field_keys,omitempty"`
	ShowWhen         []*AdminFormCondition  `protobuf:"bytes,7,rep,name=show_when,json=showWhen,proto3" json:"show_when,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminFormSection) Reset() {
	*x = AdminFormSection{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormSection) ProtoMessage() {}

func (x *AdminFormSection) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormSection.ProtoReflect.Descriptor instead.
func (*AdminFormSection) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *AdminFormSection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminFormSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminFormSection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminFormSection) GetCollapsible() bool {
	if x != nil {
		return x.Collapsible
	}
	return false
}

func (x *AdminFormSection) GetCollapsedDefault() bool {
	if x != nil {
		return x.CollapsedDefault
	}
	return false
}

func (x *AdminFormSection) GetFieldKeys() []string {
	if x != nil {
		return x.FieldKeys
	}
	return nil
}

func (x *AdminFormSection) GetShowWhen() []*AdminFormCondition {
	if x != nil {
		return x.ShowWhen
	}
	return nil
}

type AdminFormDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*AdminFormField      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	SubmitLabel   string                 `protobuf:"bytes,2,opt,name=submit_label,json=submitLabel,proto3" json:"submit_label,omitempty"`
	Sections      []*AdminFormSection    `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"` // optional; absent -> flat render of `fields`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFormDescriptor) Reset() {
	*x = AdminFormDescriptor{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFormDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFormDescriptor) ProtoMessage() {}

func (x *AdminFormDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFormDescriptor.ProtoReflect.Descriptor instead.
func (*AdminFormDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *AdminFormDescriptor) GetFields() []*AdminFormField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *AdminFormDescriptor) GetSubmitLabel() string {
	if x != nil {
		return x.SubmitLabel
	}
	return ""
}

func (x *AdminFormDescriptor) GetSections() []*AdminFormSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type HttpRouteDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Access          string                 `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Navigable       bool                   `protobuf:"varint,5,opt,name=navigable,proto3" json:"navigable,omitempty"`
	NavigationLabel string                 `protobuf:"bytes,6,opt,name=navigation_label,json=navigationLabel,proto3" json:"navigation_label,omitempty"`
	NavigationKind  string                 `protobuf:"bytes,7,opt,name=navigation_kind,json=navigationKind,proto3" json:"navigation_kind,omitempty"`
	StaticAsset     bool                   `protobuf:"varint,8,opt,name=static_asset,json=staticAsset,proto3" json:"static_asset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpRouteDescriptor) Reset() {
	*x = HttpRouteDescriptor{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRouteDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteDescriptor) ProtoMessage() {}

func (x *HttpRouteDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteDescriptor.ProtoReflect.Descriptor instead.
func (*HttpRouteDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *HttpRouteDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HttpRouteDescriptor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRouteDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRouteDescriptor) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigable() bool {
	if x != nil {
		return x.Navigable
	}
	return false
}

func (x *HttpRouteDescriptor) GetNavigationLabel() string {
	if x != nil {
		return x.NavigationLabel
	}
	return ""
}

func (x *HttpRouteDescriptor) GetNavigationKind() string {
	if x != nil {
		return x.NavigationKind
	}
	return ""
}

func (x *HttpRouteDescriptor) GetStaticAsset() bool {
	if x != nil {
		return x.StaticAsset
	}
	return false
}

type PackagedAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Integrity     string                 `protobuf:"bytes,3,opt,name=integrity,proto3" json:"integrity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagedAsset) Reset() {
	*x = PackagedAsset{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagedAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagedAsset) ProtoMessage() {}

func (x *PackagedAsset) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagedAsset.ProtoReflect.Descriptor instead.
func (*PackagedAsset) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *PackagedAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PackagedAsset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PackagedAsset) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

type CapabilityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Subscriptions []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	ConfigSchema  []*ConfigSchema        `protobuf:"bytes,6,rep,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// OAuth/OIDC flow modes the plugin supports. Only meaningful for
	// capabilities of type "auth_provider.v1". Defaults to ["password"]
	// host-side when absent (backward compat with password-only providers).
	// Valid values: "password", "oauth2".
	AuthModes []string `protobuf:"bytes,8,rep,name=auth_modes,json=authModes,proto3" json:"auth_modes,omitempty"`
	// Optional URL to a logo for this auth provider, rendered in silo's
	// login UI as the icon for a "Sign in with X" button. Plugin-served path
	// (e.g., /api/v1/plugins/<install>/assets/whmcs-logo.svg).
	IconUrl string `protobuf:"bytes,9,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// Typed watch-provider contract metadata. Only meaningful for capabilities
	// of type "watch_sync_provider.v1". Keeping this typed lets the host build
	// connection and authorization UI without launching the plugin.
	WatchSyncProvider *WatchSyncProviderDescriptor `protobuf:"bytes,10,opt,name=watch_sync_provider,json=watchSyncProvider,proto3" json:"watch_sync_provider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilityDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CapabilityDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CapabilityDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilityDescriptor) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *CapabilityDescriptor) GetConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *CapabilityDescriptor) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CapabilityDescriptor) GetAuthModes() []string {
	if x != nil {
		return x.AuthModes
	}
	return nil
}

func (x *CapabilityDescriptor) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CapabilityDescriptor) GetWatchSyncProvider() *WatchSyncProviderDescriptor {
	if x != nil {
		return x.WatchSyncProvider
	}
	return nil
}

// PluginPresentation describes a plugin for server operators and links them to
// its publisher, source, support, and release history. These values are
// self-declared by the plugin and never determine catalog approval.
type PluginPresentation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DisplayName         string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Summary             string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	DescriptionMarkdown string                 `protobuf:"bytes,3,opt,name=description_markdown,json=descriptionMarkdown,proto3" json:"description_markdown,omitempty"`
	SetupMarkdown       string                 `protobuf:"bytes,4,opt,name=setup_markdown,json=setupMarkdown,proto3" json:"setup_markdown,omitempty"`
	HomepageUrl         string                 `protobuf:"bytes,5,opt,name=homepage_url,json=homepageUrl,proto3" json:"homepage_url,omitempty"`
	SourceUrl           string                 `protobuf:"bytes,6,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SupportUrl          string                 `protobuf:"bytes,7,opt,name=support_url,json=supportUrl,proto3" json:"support_url,omitempty"`
	ChangelogUrl        string                 `protobuf:"bytes,8,opt,name=changelog_url,json=changelogUrl,proto3" json:"changelog_url,omitempty"`
	PublisherName       string                 `protobuf:"bytes,9,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	PublisherUrl        string                 `protobuf:"bytes,10,opt,name=publisher_url,json=publisherUrl,proto3" json:"publisher_url,omitempty"`
	LicenseSpdx         string                 `protobuf:"bytes,11,opt,name=license_spdx,json=licenseSpdx,proto3" json:"license_spdx,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PluginPresentation) Reset() {
	*x = PluginPresentation{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginPresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginPresentation) ProtoMessage() {}

func (x *PluginPresentation) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginPresentation.ProtoReflect.Descriptor instead.
func (*PluginPresentation) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *PluginPresentation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginPresentation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PluginPresentation) GetDescriptionMarkdown() string {
	if x != nil {
		return x.DescriptionMarkdown
	}
	return ""
}

func (x *PluginPresentation) GetSetupMarkdown() string {
	if x != nil {
		return x.SetupMarkdown
	}
	return ""
}

func (x *PluginPresentation) GetHomepageUrl() string {
	if x != nil {
		return x.HomepageUrl
	}
	return ""
}

func (x *PluginPresentation) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *PluginPresentation) GetSupportUrl() string {
	if x != nil {
		return x.SupportUrl
	}
	return ""
}

func (x *PluginPresentation) GetChangelogUrl() string {
	if x != nil {
		return x.ChangelogUrl
	}
	return ""
}

func (x *PluginPresentation) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *PluginPresentation) GetPublisherUrl() string {
	if x != nil {
		return x.PublisherUrl
	}
	return ""
}

func (x *PluginPresentation) GetLicenseSpdx() string {
	if x != nil {
		return x.LicenseSpdx
	}
	return ""
}

type PluginManifest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	PluginId           string                  `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version            string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum           string                  `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	SiloApiVersion     string                  `protobuf:"bytes,4,opt,name=silo_api_version,json=siloApiVersion,proto3" json:"silo_api_version,omitempty"`
	SupportedPlatforms []*SupportedPlatform    `protobuf:"bytes,5,rep,name=supported_platforms,json=supportedPlatforms,proto3" json:"supported_platforms,omitempty"`
	Capabilities       []*CapabilityDescriptor `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	GlobalConfigSchema []*ConfigSchema         `protobuf:"bytes,7,rep,name=global_config_schema,json=globalConfigSchema,proto3" json:"global_config_schema,omitempty"`
	UserConfigSchema   []*ConfigSchema         `protobuf:"bytes,8,rep,name=user_config_schema,json=userConfigSchema,proto3" json:"user_config_schema,omitempty"`
	HttpRoutes         []*HttpRouteDescriptor  `protobuf:"bytes,9,rep,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	Assets             []*PackagedAsset        `protobuf:"bytes,10,rep,name=assets,proto3" json:"assets,omitempty"`
	Metadata           *structpb.Struct        `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// category groups the plugin in the admin sidebar. The string is parsed
	// as a slash-delimited path so plugins can declare nested grouping —
	// e.g. "Books/Audiobooks" lands in Apps → Books → Audiobooks. Plugins
	// without a category render under "Other". The host does not validate
	// the value; the sidebar tolerates unknown segments.
	Category string `protobuf:"bytes,12,opt,name=category,proto3" json:"category,omitempty"`
	// Optional operator-facing identity, documentation, and repository links.
	// Older manifests remain valid when this block is absent.
	Presentation  *PluginPresentation `protobuf:"bytes,13,opt,name=presentation,proto3" json:"presentation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{13}
}

func (x *PluginManifest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PluginManifest) GetSiloApiVersion() string {
	if x != nil {
		return x.SiloApiVersion
	}
	return ""
}

func (x *PluginManifest) GetSupportedPlatforms() []*SupportedPlatform {
	if x != nil {
		return x.SupportedPlatforms
	}
	return nil
}

func (x *PluginManifest) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetGlobalConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.GlobalConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetUserConfigSchema() []*ConfigSchema {
	if x != nil {
		return x.UserConfigSchema
	}
	return nil
}

func (x *PluginManifest) GetHttpRoutes() []*HttpRouteDescriptor {
	if x != nil {
		return x.HttpRoutes
	}
	return nil
}

func (x *PluginManifest) GetAssets() []*PackagedAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *PluginManifest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PluginManifest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PluginManifest) GetPresentation() *PluginPresentation {
	if x != nil {
		return x.Presentation
	}
	return nil
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{14}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *PluginManifest        `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{15}
}

func (x *GetManifestResponse) GetManifest() *PluginManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*ConfigEntry         `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigureRequest) GetConfig() []*ConfigEntry {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{17}
}

type BindHostBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindHostBrokerRequest) Reset() {
	*x = BindHostBrokerRequest{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindHostBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindHostBrokerRequest) ProtoMessage() {}

func (x *BindHostBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindHostBrokerRequest.ProtoReflect.Descriptor instead.
func (*BindHostBrokerRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{18}
}

func (x *BindHostBrokerRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

type BindHostBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindHostBrokerResponse) Reset() {
	*x = BindHostBrokerResponse{}
	mi := &file_silo_plugin_v1_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindHostBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindHostBrokerResponse) ProtoMessage() {}

func (x *BindHostBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindHostBrokerResponse.ProtoReflect.Descriptor instead.
func (*BindHostBrokerResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_common_proto_rawDescGZIP(), []int{19}
}

var File_silo_plugin_v1_common_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bsilo/plugin/v1/common.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a(silo/plugin/v1/watch_sync_provider.proto\"7\n" +
	"\x11SupportedPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"\xd9\x01\n" +
	"\fConfigSchema\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vjson_schema\x18\x04 \x01(\tR\n" +
	"jsonSchema\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12B\n" +
	"\n" +
	"admin_form\x18\x06 \x01(\v2#.silo.plugin.v1.AdminFormDescriptorR\tadminForm\"_\n" +
	"\x0fAdminFormOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xf9\x04\n" +
	"\x0eAdminFormField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\acontrol\x18\x04 \x01(\x0e2 .silo.plugin.v1.AdminFormControlR\acontrol\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\x12\x16\n" +
	"\x06secret\x18\a \x01(\bR\x06secret\x12\x1c\n" +
	"\tmultiline\x18\b \x01(\bR\tmultiline\x12;\n" +
	"\rdefault_value\x18\t \x01(\v2\x16.google.protobuf.ValueR\fdefaultValue\x129\n" +
	"\aoptions\x18\n" +
	" \x03(\v2\x1f.silo.plugin.v1.AdminFormOptionR\aoptions\x12\x12\n" +
	"\x04rows\x18\v \x01(\x05R\x04rows\x12'\n" +
	"\x0fdynamic_options\x18\f \x01(\bR\x0edynamicOptions\x12?\n" +
	"\tshow_when\x18\r \x03(\v2\".silo.plugin.v1.AdminFormConditionR\bshowWhen\x12C\n" +
	"\n" +
	"validation\x18\x0e \x01(\v2#.silo.plugin.v1.AdminFormValidationR\n" +
	"validation\x122\n" +
	"\x15exclusive_group_field\x18\x0f \x01(\tR\x13exclusiveGroupField\"B\n" +
	"\x12AdminFormCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06equals\x18\x02 \x03(\tR\x06equals\"\xc3\x01\n" +
	"\x13AdminFormValidation\x12\x17\n" +
	"\ahas_min\x18\x01 \x01(\bR\x06hasMin\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x17\n" +
	"\ahas_max\x18\x03 \x01(\bR\x06hasMax\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x01R\x03max\x12\x18\n" +
	"\apattern\x18\x05 \x01(\tR\apattern\x12\x1d\n" +
	"\n" +
	"min_length\x18\x06 \x01(\x05R\tminLength\x12\x1d\n" +
	"\n" +
	"max_length\x18\a \x01(\x05R\tmaxLength\"\x8b\x02\n" +
	"\x10AdminFormSection\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vcollapsible\x18\x04 \x01(\bR\vcollapsible\x12+\n" +
	"\x11collapsed_default\x18\x05 \x01(\bR\x10collapsedDefault\x12\x1d\n" +
	"\n" +
	"field_keys\x18\x06 \x03(\tR\tfieldKeys\x12?\n" +
	"\tshow_when\x18\a \x03(\v2\".silo.plugin.v1.AdminFormConditionR\bshowWhen\"\xae\x01\n" +
	"\x13AdminFormDescriptor\x126\n" +
	"\x06fields\x18\x01 \x03(\v2\x1e.silo.plugin.v1.AdminFormFieldR\x06fields\x12!\n" +
	"\fsubmit_label\x18\x02 \x01(\tR\vsubmitLabel\x12<\n" +
	"\bsections\x18\x03 \x03(\v2 .silo.plugin.v1.AdminFormSectionR\bsections\"N\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"\xfe\x01\n" +
	"\x13HttpRouteDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06access\x18\x04 \x01(\tR\x06access\x12\x1c\n" +
	"\tnavigable\x18\x05 \x01(\bR\tnavigable\x12)\n" +
	"\x10navigation_label\x18\x06 \x01(\tR\x0fnavigationLabel\x12'\n" +
	"\x0fnavigation_kind\x18\a \x01(\tR\x0enavigationKind\x12!\n" +
	"\fstatic_asset\x18\b \x01(\bR\vstaticAsset\"d\n" +
	"\rPackagedAsset\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1c\n" +
	"\tintegrity\x18\x03 \x01(\tR\tintegrity\"\xb4\x03\n" +
	"\x14CapabilityDescriptor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12A\n" +
	"\rconfig_schema\x18\x06 \x03(\v2\x1c.silo.plugin.v1.ConfigSchemaR\fconfigSchema\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1d\n" +
	"\n" +
	"auth_modes\x18\b \x03(\tR\tauthModes\x12\x19\n" +
	"\bicon_url\x18\t \x01(\tR\aiconUrl\x12[\n" +
	"\x13watch_sync_provider\x18\n" +
	" \x01(\v2+.silo.plugin.v1.WatchSyncProviderDescriptorR\x11watchSyncProvider\"\xa2\x03\n" +
	"\x12PluginPresentation\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x121\n" +
	"\x14description_markdown\x18\x03 \x01(\tR\x13descriptionMarkdown\x12%\n" +
	"\x0esetup_markdown\x18\x04 \x01(\tR\rsetupMarkdown\x12!\n" +
	"\fhomepage_url\x18\x05 \x01(\tR\vhomepageUrl\x12\x1d\n" +
	"\n" +
	"source_url\x18\x06 \x01(\tR\tsourceUrl\x12\x1f\n" +
	"\vsupport_url\x18\a \x01(\tR\n" +
	"supportUrl\x12#\n" +
	"\rchangelog_url\x18\b \x01(\tR\fchangelogUrl\x12%\n" +
	"\x0epublisher_name\x18\t \x01(\tR\rpublisherName\x12#\n" +
	"\rpublisher_url\x18\n" +
	" \x01(\tR\fpublisherUrl\x12!\n" +
	"\flicense_spdx\x18\v \x01(\tR\vlicenseSpdx\"\xdd\x05\n" +
	"\x0ePluginManifest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12(\n" +
	"\x10silo_api_version\x18\x04 \x01(\tR\x0esiloApiVersion\x12R\n" +
	"\x13supported_platforms\x18\x05 \x03(\v2!.silo.plugin.v1.SupportedPlatformR\x12supportedPlatforms\x12H\n" +
	"\fcapabilities\x18\x06 \x03(\v2$.silo.plugin.v1.CapabilityDescriptorR\fcapabilities\x12N\n" +
	"\x14global_config_schema\x18\a \x03(\v2\x1c.silo.plugin.v1.ConfigSchemaR\x12globalConfigSchema\x12J\n" +
	"\x12user_config_schema\x18\b \x03(\v2\x1c.silo.plugin.v1.ConfigSchemaR\x10userConfigSchema\x12D\n" +
	"\vhttp_routes\x18\t \x03(\v2#.silo.plugin.v1.HttpRouteDescriptorR\n" +
	"httpRoutes\x125\n" +
	"\x06assets\x18\n" +
	" \x03(\v2\x1d.silo.plugin.v1.PackagedAssetR\x06assets\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1a\n" +
	"\bcategory\x18\f \x01(\tR\bcategory\x12F\n" +
	"\fpresentation\x18\r \x01(\v2\".silo.plugin.v1.PluginPresentationR\fpresentation\"\x14\n" +
	"\x12GetManifestRequest\"Q\n" +
	"\x13GetManifestResponse\x12:\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1e.silo.plugin.v1.PluginManifestR\bmanifest\"G\n" +
	"\x10ConfigureRequest\x123\n" +
	"\x06config\x18\x01 \x03(\v2\x1b.silo.plugin.v1.ConfigEntryR\x06config\"\x13\n" +
	"\x11ConfigureResponse\"4\n" +
	"\x15BindHostBrokerRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\"\x18\n" +
	"\x16BindHostBrokerResponse*\x97\x02\n" +
	"\x10AdminFormControl\x12\"\n" +
	"\x1eADMIN_FORM_CONTROL_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ADMIN_FORM_CONTROL_TEXT\x10\x01\x12\x1f\n" +
	"\x1bADMIN_FORM_CONTROL_TEXTAREA\x10\x02\x12\x1f\n" +
	"\x1bADMIN_FORM_CONTROL_PASSWORD\x10\x03\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_NUMBER\x10\x04\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_SWITCH\x10\x05\x12\x1d\n" +
	"\x19ADMIN_FORM_CONTROL_SELECT\x10\x06\x12#\n" +
	"\x1fADMIN_FORM_CONTROL_MULTI_SELECT\x10\a2\x94\x02\n" +
	"\aRuntime\x12V\n" +
	"\vGetManifest\x12\".silo.plugin.v1.GetManifestRequest\x1a#.silo.plugin.v1.GetManifestResponse\x12P\n" +
	"\tConfigure\x12 .silo.plugin.v1.ConfigureRequest\x1a!.silo.plugin.v1.ConfigureResponse\x12_\n" +
	"\x0eBindHostBroker\x12%.silo.plugin.v1.BindHostBrokerRequest\x1a&.silo.plugin.v1.BindHostBrokerResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_common_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_common_proto_rawDescData []byte
)

func file_silo_plugin_v1_common_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_common_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_common_proto_rawDesc), len(file_silo_plugin_v1_common_proto_rawDesc)))
	})
	return file_silo_plugin_v1_common_proto_rawDescData
}

var file_silo_plugin_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_silo_plugin_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_silo_plugin_v1_common_proto_goTypes = []any{
	(AdminFormControl)(0),               // 0: silo.plugin.v1.AdminFormControl
	(*SupportedPlatform)(nil),           // 1: silo.plugin.v1.SupportedPlatform
	(*ConfigSchema)(nil),                // 2: silo.plugin.v1.ConfigSchema
	(*AdminFormOption)(nil),             // 3: silo.plugin.v1.AdminFormOption
	(*AdminFormField)(nil),              // 4: silo.plugin.v1.AdminFormField
	(*AdminFormCondition)(nil),          // 5: silo.plugin.v1.AdminFormCondition
	(*AdminFormValidation)(nil),         // 6: silo.plugin.v1.AdminFormValidation
	(*AdminFormSection)(nil),            // 7: silo.plugin.v1.AdminFormSection
	(*AdminFormDescriptor)(nil),         // 8: silo.plugin.v1.AdminFormDescriptor
	(*ConfigEntry)(nil),                 // 9: silo.plugin.v1.ConfigEntry
	(*HttpRouteDescriptor)(nil),         // 10: silo.plugin.v1.HttpRouteDescriptor
	(*PackagedAsset)(nil),               // 11: silo.plugin.v1.PackagedAsset
	(*CapabilityDescriptor)(nil),        // 12: silo.plugin.v1.CapabilityDescriptor
	(*PluginPresentation)(nil),          // 13: silo.plugin.v1.PluginPresentation
	(*PluginManifest)(nil),              // 14: silo.plugin.v1.PluginManifest
	(*GetManifestRequest)(nil),          // 15: silo.plugin.v1.GetManifestRequest
	(*GetManifestResponse)(nil),         // 16: silo.plugin.v1.GetManifestResponse
	(*ConfigureRequest)(nil),            // 17: silo.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),           // 18: silo.plugin.v1.ConfigureResponse
	(*BindHostBrokerRequest)(nil),       // 19: silo.plugin.v1.BindHostBrokerRequest
	(*BindHostBrokerResponse)(nil),      // 20: silo.plugin.v1.BindHostBrokerResponse
	(*structpb.Value)(nil),              // 21: google.protobuf.Value
	(*structpb.Struct)(nil),             // 22: google.protobuf.Struct
	(*WatchSyncProviderDescriptor)(nil), // 23: silo.plugin.v1.WatchSyncProviderDescriptor
}
var file_silo_plugin_v1_common_proto_depIdxs = []int32{
	8,  // 0: silo.plugin.v1.ConfigSchema.admin_form:type_name -> silo.plugin.v1.AdminFormDescriptor
	0,  // 1: silo.plugin.v1.AdminFormField.control:type_name -> silo.plugin.v1.AdminFormControl
	21, // 2: silo.plugin.v1.AdminFormField.default_value:type_name -> google.protobuf.Value
	3,  // 3: silo.plugin.v1.AdminFormField.options:type_name -> silo.plugin.v1.AdminFormOption
	5,  // 4: silo.plugin.v1.AdminFormField.show_when:type_name -> silo.plugin.v1.AdminFormCondition
	6,  // 5: silo.plugin.v1.AdminFormField.validation:type_name -> silo.plugin.v1.AdminFormValidation
	5,  // 6: silo.plugin.v1.AdminFormSection.show_when:type_name -> silo.plugin.v1.AdminFormCondition
	4,  // 7: silo.plugin.v1.AdminFormDescriptor.fields:type_name -> silo.plugin.v1.AdminFormField
	7,  // 8: silo.plugin.v1.AdminFormDescriptor.sections:type_name -> silo.plugin.v1.AdminFormSection
	22, // 9: silo.plugin.v1.ConfigEntry.value:type_name -> google.protobuf.Struct
	2,  // 10: silo.plugin.v1.CapabilityDescriptor.config_schema:type_name -> silo.plugin.v1.ConfigSchema
	22, // 11: silo.plugin.v1.CapabilityDescriptor.metadata:type_name -> google.protobuf.Struct
	23, // 12: silo.plugin.v1.CapabilityDescriptor.watch_sync_provider:type_name -> silo.plugin.v1.WatchSyncProviderDescriptor
	1,  // 13: silo.plugin.v1.PluginManifest.supported_platforms:type_name -> silo.plugin.v1.SupportedPlatform
	12, // 14: silo.plugin.v1.PluginManifest.capabilities:type_name -> silo.plugin.v1.CapabilityDescriptor
	2,  // 15: silo.plugin.v1.PluginManifest.global_config_schema:type_name -> silo.plugin.v1.ConfigSchema
	2,  // 16: silo.plugin.v1.PluginManifest.user_config_schema:type_name -> silo.plugin.v1.ConfigSchema
	10, // 17: silo.plugin.v1.PluginManifest.http_routes:type_name -> silo.plugin.v1.HttpRouteDescriptor
	11, // 18: silo.plugin.v1.PluginManifest.assets:type_name -> silo.plugin.v1.PackagedAsset
	22, // 19: silo.plugin.v1.PluginManifest.metadata:type_name -> google.protobuf.Struct
	13, // 20: silo.plugin.v1.PluginManifest.presentation:type_name -> silo.plugin.v1.PluginPresentation
	14, // 21: silo.plugin.v1.GetManifestResponse.manifest:type_name -> silo.plugin.v1.PluginManifest
	9,  // 22: silo.plugin.v1.ConfigureRequest.config:type_name -> silo.plugin.v1.ConfigEntry
	15, // 23: silo.plugin.v1.Runtime.GetManifest:input_type -> silo.plugin.v1.GetManifestRequest
	17, // 24: silo.plugin.v1.Runtime.Configure:input_type -> silo.plugin.v1.ConfigureRequest
	19, // 25: silo.plugin.v1.Runtime.BindHostBroker:input_type -> silo.plugin.v1.BindHostBrokerRequest
	16, // 26: silo.plugin.v1.Runtime.GetManifest:output_type -> silo.plugin.v1.GetManifestResponse
	18, // 27: silo.plugin.v1.Runtime.Configure:output_type -> silo.plugin.v1.ConfigureResponse
	20, // 28: silo.plugin.v1.Runtime.BindHostBroker:output_type -> silo.plugin.v1.BindHostBrokerResponse
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_common_proto_init() }
func file_silo_plugin_v1_common_proto_init() {
	if File_silo_plugin_v1_common_proto != nil {
		return
	}
	file_silo_plugin_v1_watch_sync_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_common_proto_rawDesc), len(file_silo_plugin_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_common_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_common_proto_depIdxs,
		EnumInfos:         file_silo_plugin_v1_common_proto_enumTypes,
		MessageInfos:      file_silo_plugin_v1_common_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_common_proto = out.File
	file_silo_plugin_v1_common_proto_goTypes = nil
	file_silo_plugin_v1_common_proto_depIdxs = nil
}
