// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/request_router.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDescriptor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MediaType          string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // "movie" | "series"
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Year               int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	ExternalIds        map[string]string      `protobuf:"bytes,4,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsAnime            bool                   `protobuf:"varint,5,opt,name=is_anime,json=isAnime,proto3" json:"is_anime,omitempty"`
	RequesterUserId    int64                  `protobuf:"varint,6,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	RequesterProfileId string                 `protobuf:"bytes,7,opt,name=requester_profile_id,json=requesterProfileId,proto3" json:"requester_profile_id,omitempty"`
	// requester identity for plugins that attribute requests to a per-user account
	// on the downstream service (e.g. Seerr). Empty when the host cannot resolve it.
	RequesterEmail    string `protobuf:"bytes,8,opt,name=requester_email,json=requesterEmail,proto3" json:"requester_email,omitempty"`
	RequesterUsername string `protobuf:"bytes,9,opt,name=requester_username,json=requesterUsername,proto3" json:"requester_username,omitempty"`
	// seasons lists the requested season numbers of a series; 0 is Specials.
	// Empty means the whole series, which is what every request meant before
	// this field existed. Only set when media_type is "series". Plugins that
	// declare RequestRouterDescriptor.supports_seasons must fulfil only these
	// seasons; see that field for the full contract.
	Seasons       []int32 `protobuf:"varint,10,rep,packed,name=seasons,proto3" json:"seasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDescriptor) Reset() {
	*x = RequestDescriptor{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDescriptor) ProtoMessage() {}

func (x *RequestDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDescriptor.ProtoReflect.Descriptor instead.
func (*RequestDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDescriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *RequestDescriptor) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestDescriptor) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RequestDescriptor) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *RequestDescriptor) GetIsAnime() bool {
	if x != nil {
		return x.IsAnime
	}
	return false
}

func (x *RequestDescriptor) GetRequesterUserId() int64 {
	if x != nil {
		return x.RequesterUserId
	}
	return 0
}

func (x *RequestDescriptor) GetRequesterProfileId() string {
	if x != nil {
		return x.RequesterProfileId
	}
	return ""
}

func (x *RequestDescriptor) GetRequesterEmail() string {
	if x != nil {
		return x.RequesterEmail
	}
	return ""
}

func (x *RequestDescriptor) GetRequesterUsername() string {
	if x != nil {
		return x.RequesterUsername
	}
	return ""
}

func (x *RequestDescriptor) GetSeasons() []int32 {
	if x != nil {
		return x.Seasons
	}
	return nil
}

// RequestRouterDescriptor is typed request_router.v1 contract metadata that the
// host reads from the manifest without launching the plugin. An absent
// descriptor means every flag is false, which is how the host treats plugins
// built before a flag existed.
type RequestRouterDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// supports_seasons declares that Fulfill and CheckStatus honour
	// RequestDescriptor.seasons. A declaring plugin acquires only the listed
	// seasons; when the series already exists upstream it adds those seasons to
	// what is already tracked and leaves other seasons unchanged. Repeating a
	// request converges rather than duplicating work. The host sends a request
	// for only the missing seasons of a series it already has only to plugins
	// that set this flag, because other plugins would add the whole series.
	SupportsSeasons bool `protobuf:"varint,1,opt,name=supports_seasons,json=supportsSeasons,proto3" json:"supports_seasons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestRouterDescriptor) Reset() {
	*x = RequestRouterDescriptor{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRouterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRouterDescriptor) ProtoMessage() {}

func (x *RequestRouterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRouterDescriptor.ProtoReflect.Descriptor instead.
func (*RequestRouterDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRouterDescriptor) GetSupportsSeasons() bool {
	if x != nil {
		return x.SupportsSeasons
	}
	return false
}

type RouterConnection struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseUrl string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey  string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// plugin-declared config blob (e.g. service_kind, root_folder,
	// quality_profile_id)
	Config        *structpb.Struct `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterConnection) Reset() {
	*x = RouterConnection{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterConnection) ProtoMessage() {}

func (x *RouterConnection) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterConnection.ProtoReflect.Descriptor instead.
func (*RouterConnection) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{2}
}

func (x *RouterConnection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouterConnection) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *RouterConnection) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RouterConnection) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// RequestedQuality is one quality tier the host wants fulfilled. The host owns
// quality governance, so it stamps is4k rather than each plugin re-deriving it
// from the id string. id is the tier identity echoed back as
// FulfillmentTarget.quality (e.g. "1080p" / "2160p").
type RequestedQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Is4K          bool                   `protobuf:"varint,2,opt,name=is4k,proto3" json:"is4k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedQuality) Reset() {
	*x = RequestedQuality{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedQuality) ProtoMessage() {}

func (x *RequestedQuality) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedQuality.ProtoReflect.Descriptor instead.
func (*RequestedQuality) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{3}
}

func (x *RequestedQuality) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestedQuality) GetIs4K() bool {
	if x != nil {
		return x.Is4K
	}
	return false
}

type FulfillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Request       *RequestDescriptor     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Qualities     []*RequestedQuality    `protobuf:"bytes,3,rep,name=qualities,proto3" json:"qualities,omitempty"`
	Connections   []*RouterConnection    `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillRequest) Reset() {
	*x = FulfillRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillRequest) ProtoMessage() {}

func (x *FulfillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillRequest.ProtoReflect.Descriptor instead.
func (*FulfillRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{4}
}

func (x *FulfillRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *FulfillRequest) GetRequest() *RequestDescriptor {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FulfillRequest) GetQualities() []*RequestedQuality {
	if x != nil {
		return x.Qualities
	}
	return nil
}

func (x *FulfillRequest) GetConnections() []*RouterConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type FulfillmentTarget struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Quality      string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ExternalId   string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // upstream id, e.g. arr movie/series id
	// raw upstream status passed through for display; status is the
	// host-normalized value
	ExternalStatus string `protobuf:"bytes,4,opt,name=external_status,json=externalStatus,proto3" json:"external_status,omitempty"`
	// host-normalized: "queued" | "downloading" | "completed" | "failed"
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillmentTarget) Reset() {
	*x = FulfillmentTarget{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillmentTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillmentTarget) ProtoMessage() {}

func (x *FulfillmentTarget) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillmentTarget.ProtoReflect.Descriptor instead.
func (*FulfillmentTarget) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{5}
}

func (x *FulfillmentTarget) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *FulfillmentTarget) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *FulfillmentTarget) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FulfillmentTarget) GetExternalStatus() string {
	if x != nil {
		return x.ExternalStatus
	}
	return ""
}

func (x *FulfillmentTarget) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FulfillmentTarget) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FulfillResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Targets []*FulfillmentTarget   `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// set when zero targets, e.g. "no radarr instance configured"
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FulfillResponse) Reset() {
	*x = FulfillResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FulfillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulfillResponse) ProtoMessage() {}

func (x *FulfillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulfillResponse.ProtoReflect.Descriptor instead.
func (*FulfillResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{6}
}

func (x *FulfillResponse) GetTargets() []*FulfillmentTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *FulfillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quality       string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{7}
}

func (x *TargetRef) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TargetRef) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TargetRef) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type CheckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Request       *RequestDescriptor     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Targets       []*TargetRef           `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	Connections   []*RouterConnection    `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{8}
}

func (x *CheckStatusRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *CheckStatusRequest) GetRequest() *RequestDescriptor {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CheckStatusRequest) GetTargets() []*TargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CheckStatusRequest) GetConnections() []*RouterConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type TargetStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Quality      string                 `protobuf:"bytes,1,opt,name=quality,proto3" json:"quality,omitempty"`
	ConnectionId string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// host-normalized: "queued" | "downloading" | "completed" | "failed"
	Status         string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExternalStatus string `protobuf:"bytes,4,opt,name=external_status,json=externalStatus,proto3" json:"external_status,omitempty"` // raw upstream status passed through for display
	Message        string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{9}
}

func (x *TargetStatus) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *TargetStatus) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *TargetStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TargetStatus) GetExternalStatus() string {
	if x != nil {
		return x.ExternalStatus
	}
	return ""
}

func (x *TargetStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TargetStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{10}
}

func (x *CheckStatusResponse) GetStatuses() []*TargetStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ConfigOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigOption) Reset() {
	*x = ConfigOption{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOption) ProtoMessage() {}

func (x *ConfigOption) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOption.ProtoReflect.Descriptor instead.
func (*ConfigOption) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ConfigOptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*ConfigOption        `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigOptionList) Reset() {
	*x = ConfigOptionList{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigOptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOptionList) ProtoMessage() {}

func (x *ConfigOptionList) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOptionList.ProtoReflect.Descriptor instead.
func (*ConfigOptionList) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigOptionList) GetOptions() []*ConfigOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListConfigOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection    *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigOptionsRequest) Reset() {
	*x = ListConfigOptionsRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigOptionsRequest) ProtoMessage() {}

func (x *ListConfigOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigOptionsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{13}
}

func (x *ListConfigOptionsRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ListConfigOptionsRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type ListConfigOptionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keyed by config field, e.g. "root_folder"
	OptionsByField map[string]*ConfigOptionList `protobuf:"bytes,1,rep,name=options_by_field,json=optionsByField,proto3" json:"options_by_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConfigOptionsResponse) Reset() {
	*x = ListConfigOptionsResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigOptionsResponse) ProtoMessage() {}

func (x *ListConfigOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigOptionsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{14}
}

func (x *ListConfigOptionsResponse) GetOptionsByField() map[string]*ConfigOptionList {
	if x != nil {
		return x.OptionsByField
	}
	return nil
}

type TestConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection    *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionRequest) Reset() {
	*x = TestConnectionRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionRequest) ProtoMessage() {}

func (x *TestConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionRequest.ProtoReflect.Descriptor instead.
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{15}
}

func (x *TestConnectionRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *TestConnectionRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type TestConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectionResponse) Reset() {
	*x = TestConnectionResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectionResponse) ProtoMessage() {}

func (x *TestConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectionResponse.ProtoReflect.Descriptor instead.
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{16}
}

func (x *TestConnectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	Connection   *RouterConnection      `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// siblings are the other connections bound to this installation+capability, so
	// a plugin can enforce cross-connection rules (e.g. one default per service
	// type). They carry id + config only — no base_url/api_key (validation reads
	// flags, not credentials).
	Siblings      []*RouterConnection `protobuf:"bytes,3,rep,name=siblings,proto3" json:"siblings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ValidateRequest) GetConnection() *RouterConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *ValidateRequest) GetSiblings() []*RouterConnection {
	if x != nil {
		return x.Siblings
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldErrors   map[string]string      `protobuf:"bytes,1,rep,name=field_errors,json=fieldErrors,proto3" json:"field_errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // keyed by config field; empty = no field errors
	FormError     string                 `protobuf:"bytes,2,opt,name=form_error,json=formError,proto3" json:"form_error,omitempty"`                                                                                 // form-level error; empty = none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_request_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_request_router_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateResponse) GetFieldErrors() map[string]string {
	if x != nil {
		return x.FieldErrors
	}
	return nil
}

func (x *ValidateResponse) GetFormError() string {
	if x != nil {
		return x.FormError
	}
	return ""
}

var File_silo_plugin_v1_request_router_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_request_router_proto_rawDesc = "" +
	"\n" +
	"#silo/plugin/v1/request_router.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xde\x03\n" +
	"\x11RequestDescriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12U\n" +
	"\fexternal_ids\x18\x04 \x03(\v22.silo.plugin.v1.RequestDescriptor.ExternalIdsEntryR\vexternalIds\x12\x19\n" +
	"\bis_anime\x18\x05 \x01(\bR\aisAnime\x12*\n" +
	"\x11requester_user_id\x18\x06 \x01(\x03R\x0frequesterUserId\x120\n" +
	"\x14requester_profile_id\x18\a \x01(\tR\x12requesterProfileId\x12'\n" +
	"\x0frequester_email\x18\b \x01(\tR\x0erequesterEmail\x12-\n" +
	"\x12requester_username\x18\t \x01(\tR\x11requesterUsername\x12\x18\n" +
	"\aseasons\x18\n" +
	" \x03(\x05R\aseasons\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x17RequestRouterDescriptor\x12)\n" +
	"\x10supports_seasons\x18\x01 \x01(\bR\x0fsupportsSeasons\"\x87\x01\n" +
	"\x10RouterConnection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\"6\n" +
	"\x10RequestedQuality\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04is4k\x18\x02 \x01(\bR\x04is4k\"\xf6\x01\n" +
	"\x0eFulfillRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.silo.plugin.v1.RequestDescriptorR\arequest\x12>\n" +
	"\tqualities\x18\x03 \x03(\v2 .silo.plugin.v1.RequestedQualityR\tqualities\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .silo.plugin.v1.RouterConnectionR\vconnections\"\xce\x01\n" +
	"\x11FulfillmentTarget\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0fexternal_status\x18\x04 \x01(\tR\x0eexternalStatus\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"h\n" +
	"\x0fFulfillResponse\x12;\n" +
	"\atargets\x18\x01 \x03(\v2!.silo.plugin.v1.FulfillmentTargetR\atargets\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\tTargetRef\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\"\xef\x01\n" +
	"\x12CheckStatusRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12;\n" +
	"\arequest\x18\x02 \x01(\v2!.silo.plugin.v1.RequestDescriptorR\arequest\x123\n" +
	"\atargets\x18\x03 \x03(\v2\x19.silo.plugin.v1.TargetRefR\atargets\x12B\n" +
	"\vconnections\x18\x04 \x03(\v2 .silo.plugin.v1.RouterConnectionR\vconnections\"\xa8\x01\n" +
	"\fTargetStatus\x12\x18\n" +
	"\aquality\x18\x01 \x01(\tR\aquality\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fexternal_status\x18\x04 \x01(\tR\x0eexternalStatus\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"O\n" +
	"\x13CheckStatusResponse\x128\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1c.silo.plugin.v1.TargetStatusR\bstatuses\":\n" +
	"\fConfigOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"J\n" +
	"\x10ConfigOptionList\x126\n" +
	"\aoptions\x18\x01 \x03(\v2\x1c.silo.plugin.v1.ConfigOptionR\aoptions\"\x81\x01\n" +
	"\x18ListConfigOptionsRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\"\xe9\x01\n" +
	"\x19ListConfigOptionsResponse\x12g\n" +
	"\x10options_by_field\x18\x01 \x03(\v2=.silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntryR\x0eoptionsByField\x1ac\n" +
	"\x13OptionsByFieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .silo.plugin.v1.ConfigOptionListR\x05value:\x028\x01\"~\n" +
	"\x15TestConnectionRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\"B\n" +
	"\x16TestConnectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb6\x01\n" +
	"\x0fValidateRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12@\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2 .silo.plugin.v1.RouterConnectionR\n" +
	"connection\x12<\n" +
	"\bsiblings\x18\x03 \x03(\v2 .silo.plugin.v1.RouterConnectionR\bsiblings\"\xc7\x01\n" +
	"\x10ValidateResponse\x12T\n" +
	"\ffield_errors\x18\x01 \x03(\v21.silo.plugin.v1.ValidateResponse.FieldErrorsEntryR\vfieldErrors\x12\x1d\n" +
	"\n" +
	"form_error\x18\x02 \x01(\tR\tformError\x1a>\n" +
	"\x10FieldErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcd\x03\n" +
	"\rRequestRouter\x12J\n" +
	"\aFulfill\x12\x1e.silo.plugin.v1.FulfillRequest\x1a\x1f.silo.plugin.v1.FulfillResponse\x12V\n" +
	"\vCheckStatus\x12\".silo.plugin.v1.CheckStatusRequest\x1a#.silo.plugin.v1.CheckStatusResponse\x12h\n" +
	"\x11ListConfigOptions\x12(.silo.plugin.v1.ListConfigOptionsRequest\x1a).silo.plugin.v1.ListConfigOptionsResponse\x12_\n" +
	"\x0eTestConnection\x12%.silo.plugin.v1.TestConnectionRequest\x1a&.silo.plugin.v1.TestConnectionResponse\x12M\n" +
	"\bValidate\x12\x1f.silo.plugin.v1.ValidateRequest\x1a .silo.plugin.v1.ValidateResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_request_router_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_request_router_proto_rawDescData []byte
)

func file_silo_plugin_v1_request_router_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_request_router_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_request_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_request_router_proto_rawDesc), len(file_silo_plugin_v1_request_router_proto_rawDesc)))
	})
	return file_silo_plugin_v1_request_router_proto_rawDescData
}

var file_silo_plugin_v1_request_router_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_silo_plugin_v1_request_router_proto_goTypes = []any{
	(*RequestDescriptor)(nil),         // 0: silo.plugin.v1.RequestDescriptor
	(*RequestRouterDescriptor)(nil),   // 1: silo.plugin.v1.RequestRouterDescriptor
	(*RouterConnection)(nil),          // 2: silo.plugin.v1.RouterConnection
	(*RequestedQuality)(nil),          // 3: silo.plugin.v1.RequestedQuality
	(*FulfillRequest)(nil),            // 4: silo.plugin.v1.FulfillRequest
	(*FulfillmentTarget)(nil),         // 5: silo.plugin.v1.FulfillmentTarget
	(*FulfillResponse)(nil),           // 6: silo.plugin.v1.FulfillResponse
	(*TargetRef)(nil),                 // 7: silo.plugin.v1.TargetRef
	(*CheckStatusRequest)(nil),        // 8: silo.plugin.v1.CheckStatusRequest
	(*TargetStatus)(nil),              // 9: silo.plugin.v1.TargetStatus
	(*CheckStatusResponse)(nil),       // 10: silo.plugin.v1.CheckStatusResponse
	(*ConfigOption)(nil),              // 11: silo.plugin.v1.ConfigOption
	(*ConfigOptionList)(nil),          // 12: silo.plugin.v1.ConfigOptionList
	(*ListConfigOptionsRequest)(nil),  // 13: silo.plugin.v1.ListConfigOptionsRequest
	(*ListConfigOptionsResponse)(nil), // 14: silo.plugin.v1.ListConfigOptionsResponse
	(*TestConnectionRequest)(nil),     // 15: silo.plugin.v1.TestConnectionRequest
	(*TestConnectionResponse)(nil),    // 16: silo.plugin.v1.TestConnectionResponse
	(*ValidateRequest)(nil),           // 17: silo.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil),          // 18: silo.plugin.v1.ValidateResponse
	nil,                               // 19: silo.plugin.v1.RequestDescriptor.ExternalIdsEntry
	nil,                               // 20: silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry
	nil,                               // 21: silo.plugin.v1.ValidateResponse.FieldErrorsEntry
	(*structpb.Struct)(nil),           // 22: google.protobuf.Struct
}
var file_silo_plugin_v1_request_router_proto_depIdxs = []int32{
	19, // 0: silo.plugin.v1.RequestDescriptor.external_ids:type_name -> silo.plugin.v1.RequestDescriptor.ExternalIdsEntry
	22, // 1: silo.plugin.v1.RouterConnection.config:type_name -> google.protobuf.Struct
	0,  // 2: silo.plugin.v1.FulfillRequest.request:type_name -> silo.plugin.v1.RequestDescriptor
	3,  // 3: silo.plugin.v1.FulfillRequest.qualities:type_name -> silo.plugin.v1.RequestedQuality
	2,  // 4: silo.plugin.v1.FulfillRequest.connections:type_name -> silo.plugin.v1.RouterConnection
	5,  // 5: silo.plugin.v1.FulfillResponse.targets:type_name -> silo.plugin.v1.FulfillmentTarget
	0,  // 6: silo.plugin.v1.CheckStatusRequest.request:type_name -> silo.plugin.v1.RequestDescriptor
	7,  // 7: silo.plugin.v1.CheckStatusRequest.targets:type_name -> silo.plugin.v1.TargetRef
	2,  // 8: silo.plugin.v1.CheckStatusRequest.connections:type_name -> silo.plugin.v1.RouterConnection
	9,  // 9: silo.plugin.v1.CheckStatusResponse.statuses:type_name -> silo.plugin.v1.TargetStatus
	11, // 10: silo.plugin.v1.ConfigOptionList.options:type_name -> silo.plugin.v1.ConfigOption
	2,  // 11: silo.plugin.v1.ListConfigOptionsRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	20, // 12: silo.plugin.v1.ListConfigOptionsResponse.options_by_field:type_name -> silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry
	2,  // 13: silo.plugin.v1.TestConnectionRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	2,  // 14: silo.plugin.v1.ValidateRequest.connection:type_name -> silo.plugin.v1.RouterConnection
	2,  // 15: silo.plugin.v1.ValidateRequest.siblings:type_name -> silo.plugin.v1.RouterConnection
	21, // 16: silo.plugin.v1.ValidateResponse.field_errors:type_name -> silo.plugin.v1.ValidateResponse.FieldErrorsEntry
	12, // 17: silo.plugin.v1.ListConfigOptionsResponse.OptionsByFieldEntry.value:type_name -> silo.plugin.v1.ConfigOptionList
	4,  // 18: silo.plugin.v1.RequestRouter.Fulfill:input_type -> silo.plugin.v1.FulfillRequest
	8,  // 19: silo.plugin.v1.RequestRouter.CheckStatus:input_type -> silo.plugin.v1.CheckStatusRequest
	13, // 20: silo.plugin.v1.RequestRouter.ListConfigOptions:input_type -> silo.plugin.v1.ListConfigOptionsRequest
	15, // 21: silo.plugin.v1.RequestRouter.TestConnection:input_type -> silo.plugin.v1.TestConnectionRequest
	17, // 22: silo.plugin.v1.RequestRouter.Validate:input_type -> silo.plugin.v1.ValidateRequest
	6,  // 23: silo.plugin.v1.RequestRouter.Fulfill:output_type -> silo.plugin.v1.FulfillResponse
	10, // 24: silo.plugin.v1.RequestRouter.CheckStatus:output_type -> silo.plugin.v1.CheckStatusResponse
	14, // 25: silo.plugin.v1.RequestRouter.ListConfigOptions:output_type -> silo.plugin.v1.ListConfigOptionsResponse
	16, // 26: silo.plugin.v1.RequestRouter.TestConnection:output_type -> silo.plugin.v1.TestConnectionResponse
	18, // 27: silo.plugin.v1.RequestRouter.Validate:output_type -> silo.plugin.v1.ValidateResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_request_router_proto_init() }
func file_silo_plugin_v1_request_router_proto_init() {
	if File_silo_plugin_v1_request_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_request_router_proto_rawDesc), len(file_silo_plugin_v1_request_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_request_router_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_request_router_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_request_router_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_request_router_proto = out.File
	file_silo_plugin_v1_request_router_proto_goTypes = nil
	file_silo_plugin_v1_request_router_proto_depIdxs = nil
}
