// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/runtime_host.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeHost_PublishEvent_FullMethodName               = "/silo.plugin.v1.RuntimeHost/PublishEvent"
	RuntimeHost_PublishEventTo_FullMethodName             = "/silo.plugin.v1.RuntimeHost/PublishEventTo"
	RuntimeHost_PublishEventToInstallation_FullMethodName = "/silo.plugin.v1.RuntimeHost/PublishEventToInstallation"
	RuntimeHost_GetHostInfo_FullMethodName                = "/silo.plugin.v1.RuntimeHost/GetHostInfo"
	RuntimeHost_ListLibraries_FullMethodName              = "/silo.plugin.v1.RuntimeHost/ListLibraries"
	RuntimeHost_CheckMediaPresence_FullMethodName         = "/silo.plugin.v1.RuntimeHost/CheckMediaPresence"
	RuntimeHost_ListInstalledPlugins_FullMethodName       = "/silo.plugin.v1.RuntimeHost/ListInstalledPlugins"
	RuntimeHost_SetGlobalConfigEntry_FullMethodName       = "/silo.plugin.v1.RuntimeHost/SetGlobalConfigEntry"
	RuntimeHost_ListLibraryMedia_FullMethodName           = "/silo.plugin.v1.RuntimeHost/ListLibraryMedia"
	RuntimeHost_GetCatalogStats_FullMethodName            = "/silo.plugin.v1.RuntimeHost/GetCatalogStats"
	RuntimeHost_ResolveCatalogImageURLs_FullMethodName    = "/silo.plugin.v1.RuntimeHost/ResolveCatalogImageURLs"
	RuntimeHost_MintScopedStream_FullMethodName           = "/silo.plugin.v1.RuntimeHost/MintScopedStream"
	RuntimeHost_CallPluginHTTP_FullMethodName             = "/silo.plugin.v1.RuntimeHost/CallPluginHTTP"
	RuntimeHost_UpsertVirtualMedia_FullMethodName         = "/silo.plugin.v1.RuntimeHost/UpsertVirtualMedia"
	RuntimeHost_ReconcileVirtualMedia_FullMethodName      = "/silo.plugin.v1.RuntimeHost/ReconcileVirtualMedia"
)

// RuntimeHostClient is the client API for RuntimeHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeHost is implemented by the silo host. Plugins dial it via the
// go-plugin gRPC broker. See pkg/pluginsdk/runtimehost for a typed client.
type RuntimeHostClient interface {
	// PublishEvent publishes an event onto the host's event bus.
	// The host server stamps the calling plugin's ID server-side and
	// auto-prefixes event_name with "plugin.<plugin_id>." so that plugins
	// cannot forge core event names.
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	// PublishEventTo publishes an event addressed to one target plugin_id.
	PublishEventTo(ctx context.Context, in *PublishEventToRequest, opts ...grpc.CallOption) (*PublishEventToResponse, error)
	// PublishEventToInstallation publishes an event addressed to one specific
	// plugin installation. Use this when the caller discovered a peer through
	// ListInstalledPlugins and needs to avoid plugin_id ambiguity.
	PublishEventToInstallation(ctx context.Context, in *PublishEventToInstallationRequest, opts ...grpc.CallOption) (*PublishEventToInstallationResponse, error)
	// GetHostInfo returns public-safe host URLs and identity metadata plugins can
	// use when constructing callback URLs or external-facing links.
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
	// ListLibraries returns libraries visible in the host catalog.
	// If user_id is empty, all libraries are returned (admin context).
	ListLibraries(ctx context.Context, in *ListLibrariesRequest, opts ...grpc.CallOption) (*ListLibrariesResponse, error)
	// CheckMediaPresence reports which of the requested external IDs already
	// exist in the host catalog. v1 supports provider="tmdb" only.
	CheckMediaPresence(ctx context.Context, in *CheckMediaPresenceRequest, opts ...grpc.CallOption) (*CheckMediaPresenceResponse, error)
	// ListInstalledPlugins returns installed plugins and their advertised
	// capabilities so plugins can discover peers by capability.
	ListInstalledPlugins(ctx context.Context, in *ListInstalledPluginsRequest, opts ...grpc.CallOption) (*ListInstalledPluginsResponse, error)
	// SetGlobalConfigEntry persists a plugin-owned global config entry for the
	// calling plugin installation.
	SetGlobalConfigEntry(ctx context.Context, in *SetGlobalConfigEntryRequest, opts ...grpc.CallOption) (*SetGlobalConfigEntryResponse, error)
	// ListLibraryMedia returns public-safe catalog metadata from the host
	// libraries. It is intended for browse/search surfaces; it must not include
	// filesystem paths, stream URLs, or other playback grants.
	ListLibraryMedia(ctx context.Context, in *ListLibraryMediaRequest, opts ...grpc.CallOption) (*ListLibraryMediaResponse, error)
	// GetCatalogStats returns aggregate public-safe counts for host libraries.
	GetCatalogStats(ctx context.Context, in *GetCatalogStatsRequest, opts ...grpc.CallOption) (*GetCatalogStatsResponse, error)
	// ResolveCatalogImageURLs resolves stored catalog image paths using the
	// host's configured image resolver, returning browser-usable URLs.
	ResolveCatalogImageURLs(ctx context.Context, in *ResolveCatalogImageURLsRequest, opts ...grpc.CallOption) (*ResolveCatalogImageURLsResponse, error)
	// MintScopedStream mints a short-lived, narrowly scoped stream URL for a
	// plugin-owned public access workflow such as guest passes.
	MintScopedStream(ctx context.Context, in *MintScopedStreamRequest, opts ...grpc.CallOption) (*MintScopedStreamResponse, error)
	// CallPluginHTTP invokes another installed plugin's HttpRoutes handler
	// through the host control plane. Calls are treated as authenticated
	// service-to-service traffic, but never as admin traffic.
	CallPluginHTTP(ctx context.Context, in *CallPluginHTTPRequest, opts ...grpc.CallOption) (*CallPluginHTTPResponse, error)
	// UpsertVirtualMedia transactionally registers plugin-owned virtual media
	// in a host library. The host validates library compatibility, owns all
	// catalog writes, and emits the same invalidation signals as a scanner.
	UpsertVirtualMedia(ctx context.Context, in *UpsertVirtualMediaRequest, opts ...grpc.CallOption) (*UpsertVirtualMediaResponse, error)
	// ReconcileVirtualMedia removes plugin-owned virtual media for a source
	// that is no longer present in the plugin's desired set.
	ReconcileVirtualMedia(ctx context.Context, in *ReconcileVirtualMediaRequest, opts ...grpc.CallOption) (*ReconcileVirtualMediaResponse, error)
}

type runtimeHostClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeHostClient(cc grpc.ClientConnInterface) RuntimeHostClient {
	return &runtimeHostClient{cc}
}

func (c *runtimeHostClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) PublishEventTo(ctx context.Context, in *PublishEventToRequest, opts ...grpc.CallOption) (*PublishEventToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventToResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_PublishEventTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) PublishEventToInstallation(ctx context.Context, in *PublishEventToInstallationRequest, opts ...grpc.CallOption) (*PublishEventToInstallationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventToInstallationResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_PublishEventToInstallation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_GetHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) ListLibraries(ctx context.Context, in *ListLibrariesRequest, opts ...grpc.CallOption) (*ListLibrariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLibrariesResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_ListLibraries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) CheckMediaPresence(ctx context.Context, in *CheckMediaPresenceRequest, opts ...grpc.CallOption) (*CheckMediaPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMediaPresenceResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_CheckMediaPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) ListInstalledPlugins(ctx context.Context, in *ListInstalledPluginsRequest, opts ...grpc.CallOption) (*ListInstalledPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstalledPluginsResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_ListInstalledPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) SetGlobalConfigEntry(ctx context.Context, in *SetGlobalConfigEntryRequest, opts ...grpc.CallOption) (*SetGlobalConfigEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetGlobalConfigEntryResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_SetGlobalConfigEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) ListLibraryMedia(ctx context.Context, in *ListLibraryMediaRequest, opts ...grpc.CallOption) (*ListLibraryMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLibraryMediaResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_ListLibraryMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) GetCatalogStats(ctx context.Context, in *GetCatalogStatsRequest, opts ...grpc.CallOption) (*GetCatalogStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogStatsResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_GetCatalogStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) ResolveCatalogImageURLs(ctx context.Context, in *ResolveCatalogImageURLsRequest, opts ...grpc.CallOption) (*ResolveCatalogImageURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCatalogImageURLsResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_ResolveCatalogImageURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) MintScopedStream(ctx context.Context, in *MintScopedStreamRequest, opts ...grpc.CallOption) (*MintScopedStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintScopedStreamResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_MintScopedStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) CallPluginHTTP(ctx context.Context, in *CallPluginHTTPRequest, opts ...grpc.CallOption) (*CallPluginHTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallPluginHTTPResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_CallPluginHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) UpsertVirtualMedia(ctx context.Context, in *UpsertVirtualMediaRequest, opts ...grpc.CallOption) (*UpsertVirtualMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertVirtualMediaResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_UpsertVirtualMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHostClient) ReconcileVirtualMedia(ctx context.Context, in *ReconcileVirtualMediaRequest, opts ...grpc.CallOption) (*ReconcileVirtualMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileVirtualMediaResponse)
	err := c.cc.Invoke(ctx, RuntimeHost_ReconcileVirtualMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeHostServer is the server API for RuntimeHost service.
// All implementations should embed UnimplementedRuntimeHostServer
// for forward compatibility.
//
// RuntimeHost is implemented by the silo host. Plugins dial it via the
// go-plugin gRPC broker. See pkg/pluginsdk/runtimehost for a typed client.
type RuntimeHostServer interface {
	// PublishEvent publishes an event onto the host's event bus.
	// The host server stamps the calling plugin's ID server-side and
	// auto-prefixes event_name with "plugin.<plugin_id>." so that plugins
	// cannot forge core event names.
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	// PublishEventTo publishes an event addressed to one target plugin_id.
	PublishEventTo(context.Context, *PublishEventToRequest) (*PublishEventToResponse, error)
	// PublishEventToInstallation publishes an event addressed to one specific
	// plugin installation. Use this when the caller discovered a peer through
	// ListInstalledPlugins and needs to avoid plugin_id ambiguity.
	PublishEventToInstallation(context.Context, *PublishEventToInstallationRequest) (*PublishEventToInstallationResponse, error)
	// GetHostInfo returns public-safe host URLs and identity metadata plugins can
	// use when constructing callback URLs or external-facing links.
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	// ListLibraries returns libraries visible in the host catalog.
	// If user_id is empty, all libraries are returned (admin context).
	ListLibraries(context.Context, *ListLibrariesRequest) (*ListLibrariesResponse, error)
	// CheckMediaPresence reports which of the requested external IDs already
	// exist in the host catalog. v1 supports provider="tmdb" only.
	CheckMediaPresence(context.Context, *CheckMediaPresenceRequest) (*CheckMediaPresenceResponse, error)
	// ListInstalledPlugins returns installed plugins and their advertised
	// capabilities so plugins can discover peers by capability.
	ListInstalledPlugins(context.Context, *ListInstalledPluginsRequest) (*ListInstalledPluginsResponse, error)
	// SetGlobalConfigEntry persists a plugin-owned global config entry for the
	// calling plugin installation.
	SetGlobalConfigEntry(context.Context, *SetGlobalConfigEntryRequest) (*SetGlobalConfigEntryResponse, error)
	// ListLibraryMedia returns public-safe catalog metadata from the host
	// libraries. It is intended for browse/search surfaces; it must not include
	// filesystem paths, stream URLs, or other playback grants.
	ListLibraryMedia(context.Context, *ListLibraryMediaRequest) (*ListLibraryMediaResponse, error)
	// GetCatalogStats returns aggregate public-safe counts for host libraries.
	GetCatalogStats(context.Context, *GetCatalogStatsRequest) (*GetCatalogStatsResponse, error)
	// ResolveCatalogImageURLs resolves stored catalog image paths using the
	// host's configured image resolver, returning browser-usable URLs.
	ResolveCatalogImageURLs(context.Context, *ResolveCatalogImageURLsRequest) (*ResolveCatalogImageURLsResponse, error)
	// MintScopedStream mints a short-lived, narrowly scoped stream URL for a
	// plugin-owned public access workflow such as guest passes.
	MintScopedStream(context.Context, *MintScopedStreamRequest) (*MintScopedStreamResponse, error)
	// CallPluginHTTP invokes another installed plugin's HttpRoutes handler
	// through the host control plane. Calls are treated as authenticated
	// service-to-service traffic, but never as admin traffic.
	CallPluginHTTP(context.Context, *CallPluginHTTPRequest) (*CallPluginHTTPResponse, error)
	// UpsertVirtualMedia transactionally registers plugin-owned virtual media
	// in a host library. The host validates library compatibility, owns all
	// catalog writes, and emits the same invalidation signals as a scanner.
	UpsertVirtualMedia(context.Context, *UpsertVirtualMediaRequest) (*UpsertVirtualMediaResponse, error)
	// ReconcileVirtualMedia removes plugin-owned virtual media for a source
	// that is no longer present in the plugin's desired set.
	ReconcileVirtualMedia(context.Context, *ReconcileVirtualMediaRequest) (*ReconcileVirtualMediaResponse, error)
}

// UnimplementedRuntimeHostServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeHostServer struct{}

func (UnimplementedRuntimeHostServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedRuntimeHostServer) PublishEventTo(context.Context, *PublishEventToRequest) (*PublishEventToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEventTo not implemented")
}
func (UnimplementedRuntimeHostServer) PublishEventToInstallation(context.Context, *PublishEventToInstallationRequest) (*PublishEventToInstallationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEventToInstallation not implemented")
}
func (UnimplementedRuntimeHostServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedRuntimeHostServer) ListLibraries(context.Context, *ListLibrariesRequest) (*ListLibrariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLibraries not implemented")
}
func (UnimplementedRuntimeHostServer) CheckMediaPresence(context.Context, *CheckMediaPresenceRequest) (*CheckMediaPresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMediaPresence not implemented")
}
func (UnimplementedRuntimeHostServer) ListInstalledPlugins(context.Context, *ListInstalledPluginsRequest) (*ListInstalledPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstalledPlugins not implemented")
}
func (UnimplementedRuntimeHostServer) SetGlobalConfigEntry(context.Context, *SetGlobalConfigEntryRequest) (*SetGlobalConfigEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGlobalConfigEntry not implemented")
}
func (UnimplementedRuntimeHostServer) ListLibraryMedia(context.Context, *ListLibraryMediaRequest) (*ListLibraryMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLibraryMedia not implemented")
}
func (UnimplementedRuntimeHostServer) GetCatalogStats(context.Context, *GetCatalogStatsRequest) (*GetCatalogStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCatalogStats not implemented")
}
func (UnimplementedRuntimeHostServer) ResolveCatalogImageURLs(context.Context, *ResolveCatalogImageURLsRequest) (*ResolveCatalogImageURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCatalogImageURLs not implemented")
}
func (UnimplementedRuntimeHostServer) MintScopedStream(context.Context, *MintScopedStreamRequest) (*MintScopedStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintScopedStream not implemented")
}
func (UnimplementedRuntimeHostServer) CallPluginHTTP(context.Context, *CallPluginHTTPRequest) (*CallPluginHTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallPluginHTTP not implemented")
}
func (UnimplementedRuntimeHostServer) UpsertVirtualMedia(context.Context, *UpsertVirtualMediaRequest) (*UpsertVirtualMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertVirtualMedia not implemented")
}
func (UnimplementedRuntimeHostServer) ReconcileVirtualMedia(context.Context, *ReconcileVirtualMediaRequest) (*ReconcileVirtualMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileVirtualMedia not implemented")
}
func (UnimplementedRuntimeHostServer) testEmbeddedByValue() {}

// UnsafeRuntimeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeHostServer will
// result in compilation errors.
type UnsafeRuntimeHostServer interface {
	mustEmbedUnimplementedRuntimeHostServer()
}

func RegisterRuntimeHostServer(s grpc.ServiceRegistrar, srv RuntimeHostServer) {
	// If the following call panics, it indicates UnimplementedRuntimeHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeHost_ServiceDesc, srv)
}

func _RuntimeHost_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_PublishEventTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).PublishEventTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_PublishEventTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).PublishEventTo(ctx, req.(*PublishEventToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_PublishEventToInstallation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventToInstallationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).PublishEventToInstallation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_PublishEventToInstallation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).PublishEventToInstallation(ctx, req.(*PublishEventToInstallationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_ListLibraries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLibrariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).ListLibraries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_ListLibraries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).ListLibraries(ctx, req.(*ListLibrariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_CheckMediaPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMediaPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).CheckMediaPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_CheckMediaPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).CheckMediaPresence(ctx, req.(*CheckMediaPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_ListInstalledPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstalledPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).ListInstalledPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_ListInstalledPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).ListInstalledPlugins(ctx, req.(*ListInstalledPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_SetGlobalConfigEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGlobalConfigEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).SetGlobalConfigEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_SetGlobalConfigEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).SetGlobalConfigEntry(ctx, req.(*SetGlobalConfigEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_ListLibraryMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLibraryMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).ListLibraryMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_ListLibraryMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).ListLibraryMedia(ctx, req.(*ListLibraryMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_GetCatalogStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).GetCatalogStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_GetCatalogStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).GetCatalogStats(ctx, req.(*GetCatalogStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_ResolveCatalogImageURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCatalogImageURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).ResolveCatalogImageURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_ResolveCatalogImageURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).ResolveCatalogImageURLs(ctx, req.(*ResolveCatalogImageURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_MintScopedStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintScopedStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).MintScopedStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_MintScopedStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).MintScopedStream(ctx, req.(*MintScopedStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_CallPluginHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallPluginHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).CallPluginHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_CallPluginHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).CallPluginHTTP(ctx, req.(*CallPluginHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_UpsertVirtualMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertVirtualMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).UpsertVirtualMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_UpsertVirtualMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).UpsertVirtualMedia(ctx, req.(*UpsertVirtualMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHost_ReconcileVirtualMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileVirtualMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHostServer).ReconcileVirtualMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeHost_ReconcileVirtualMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHostServer).ReconcileVirtualMedia(ctx, req.(*ReconcileVirtualMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeHost_ServiceDesc is the grpc.ServiceDesc for RuntimeHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.RuntimeHost",
	HandlerType: (*RuntimeHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishEvent",
			Handler:    _RuntimeHost_PublishEvent_Handler,
		},
		{
			MethodName: "PublishEventTo",
			Handler:    _RuntimeHost_PublishEventTo_Handler,
		},
		{
			MethodName: "PublishEventToInstallation",
			Handler:    _RuntimeHost_PublishEventToInstallation_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _RuntimeHost_GetHostInfo_Handler,
		},
		{
			MethodName: "ListLibraries",
			Handler:    _RuntimeHost_ListLibraries_Handler,
		},
		{
			MethodName: "CheckMediaPresence",
			Handler:    _RuntimeHost_CheckMediaPresence_Handler,
		},
		{
			MethodName: "ListInstalledPlugins",
			Handler:    _RuntimeHost_ListInstalledPlugins_Handler,
		},
		{
			MethodName: "SetGlobalConfigEntry",
			Handler:    _RuntimeHost_SetGlobalConfigEntry_Handler,
		},
		{
			MethodName: "ListLibraryMedia",
			Handler:    _RuntimeHost_ListLibraryMedia_Handler,
		},
		{
			MethodName: "GetCatalogStats",
			Handler:    _RuntimeHost_GetCatalogStats_Handler,
		},
		{
			MethodName: "ResolveCatalogImageURLs",
			Handler:    _RuntimeHost_ResolveCatalogImageURLs_Handler,
		},
		{
			MethodName: "MintScopedStream",
			Handler:    _RuntimeHost_MintScopedStream_Handler,
		},
		{
			MethodName: "CallPluginHTTP",
			Handler:    _RuntimeHost_CallPluginHTTP_Handler,
		},
		{
			MethodName: "UpsertVirtualMedia",
			Handler:    _RuntimeHost_UpsertVirtualMedia_Handler,
		},
		{
			MethodName: "ReconcileVirtualMedia",
			Handler:    _RuntimeHost_ReconcileVirtualMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/runtime_host.proto",
}
