// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/runtime_host.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertVirtualMediaRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	LibraryId    string                 `protobuf:"bytes,1,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	MediaType    string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // "movie" or "series"
	Title        string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year         int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	ImdbId       string                 `protobuf:"bytes,5,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	TmdbId       string                 `protobuf:"bytes,6,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	TvdbId       string                 `protobuf:"bytes,7,opt,name=tvdb_id,json=tvdbId,proto3" json:"tvdb_id,omitempty"`
	Overview     string                 `protobuf:"bytes,8,opt,name=overview,proto3" json:"overview,omitempty"`
	Genres       []string               `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	PosterPath   string                 `protobuf:"bytes,10,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath string                 `protobuf:"bytes,11,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	VirtualUri   string                 `protobuf:"bytes,12,opt,name=virtual_uri,json=virtualUri,proto3" json:"virtual_uri,omitempty"`
	Episodes     []*VirtualEpisode      `protobuf:"bytes,13,rep,name=episodes,proto3" json:"episodes,omitempty"`
	// Canonical catalog runtime. Playback may use a verified source duration
	// for the active session without overwriting this value.
	RuntimeMinutes int32 `protobuf:"varint,14,opt,name=runtime_minutes,json=runtimeMinutes,proto3" json:"runtime_minutes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertVirtualMediaRequest) Reset() {
	*x = UpsertVirtualMediaRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertVirtualMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertVirtualMediaRequest) ProtoMessage() {}

func (x *UpsertVirtualMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertVirtualMediaRequest.ProtoReflect.Descriptor instead.
func (*UpsertVirtualMediaRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertVirtualMediaRequest) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpsertVirtualMediaRequest) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetTmdbId() string {
	if x != nil {
		return x.TmdbId
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetTvdbId() string {
	if x != nil {
		return x.TvdbId
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *UpsertVirtualMediaRequest) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetVirtualUri() string {
	if x != nil {
		return x.VirtualUri
	}
	return ""
}

func (x *UpsertVirtualMediaRequest) GetEpisodes() []*VirtualEpisode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *UpsertVirtualMediaRequest) GetRuntimeMinutes() int32 {
	if x != nil {
		return x.RuntimeMinutes
	}
	return 0
}

type VirtualEpisode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SeasonNumber   int32                  `protobuf:"varint,1,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber  int32                  `protobuf:"varint,2,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Overview       string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	AirDateUnix    int64                  `protobuf:"varint,5,opt,name=air_date_unix,json=airDateUnix,proto3" json:"air_date_unix,omitempty"`
	RuntimeMinutes int32                  `protobuf:"varint,6,opt,name=runtime_minutes,json=runtimeMinutes,proto3" json:"runtime_minutes,omitempty"`
	StillPath      string                 `protobuf:"bytes,7,opt,name=still_path,json=stillPath,proto3" json:"still_path,omitempty"`
	VirtualUri     string                 `protobuf:"bytes,8,opt,name=virtual_uri,json=virtualUri,proto3" json:"virtual_uri,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VirtualEpisode) Reset() {
	*x = VirtualEpisode{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualEpisode) ProtoMessage() {}

func (x *VirtualEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualEpisode.ProtoReflect.Descriptor instead.
func (*VirtualEpisode) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualEpisode) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *VirtualEpisode) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *VirtualEpisode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VirtualEpisode) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *VirtualEpisode) GetAirDateUnix() int64 {
	if x != nil {
		return x.AirDateUnix
	}
	return 0
}

func (x *VirtualEpisode) GetRuntimeMinutes() int32 {
	if x != nil {
		return x.RuntimeMinutes
	}
	return 0
}

func (x *VirtualEpisode) GetStillPath() string {
	if x != nil {
		return x.StillPath
	}
	return ""
}

func (x *VirtualEpisode) GetVirtualUri() string {
	if x != nil {
		return x.VirtualUri
	}
	return ""
}

type UpsertVirtualMediaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaId          string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	LibraryId        string                 `protobuf:"bytes,2,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	EpisodesUpserted int32                  `protobuf:"varint,3,opt,name=episodes_upserted,json=episodesUpserted,proto3" json:"episodes_upserted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpsertVirtualMediaResponse) Reset() {
	*x = UpsertVirtualMediaResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertVirtualMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertVirtualMediaResponse) ProtoMessage() {}

func (x *UpsertVirtualMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertVirtualMediaResponse.ProtoReflect.Descriptor instead.
func (*UpsertVirtualMediaResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertVirtualMediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UpsertVirtualMediaResponse) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *UpsertVirtualMediaResponse) GetEpisodesUpserted() int32 {
	if x != nil {
		return x.EpisodesUpserted
	}
	return 0
}

type PublishEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unprefixed event name in the plugin's namespace, e.g. "approved".
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Arbitrary JSON-shaped payload.
	Payload       *structpb.Struct `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{3}
}

func (x *PublishEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{4}
}

type PublishEventToRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target plugin_id, e.g. "silo.requests".
	TargetPluginId string `protobuf:"bytes,1,opt,name=target_plugin_id,json=targetPluginId,proto3" json:"target_plugin_id,omitempty"`
	// Unprefixed event name in the calling plugin's namespace.
	EventName string `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Arbitrary JSON-shaped payload.
	Payload       *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventToRequest) Reset() {
	*x = PublishEventToRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventToRequest) ProtoMessage() {}

func (x *PublishEventToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventToRequest.ProtoReflect.Descriptor instead.
func (*PublishEventToRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{5}
}

func (x *PublishEventToRequest) GetTargetPluginId() string {
	if x != nil {
		return x.TargetPluginId
	}
	return ""
}

func (x *PublishEventToRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PublishEventToRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishEventToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventToResponse) Reset() {
	*x = PublishEventToResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventToResponse) ProtoMessage() {}

func (x *PublishEventToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventToResponse.ProtoReflect.Descriptor instead.
func (*PublishEventToResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{6}
}

type PublishEventToInstallationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TargetInstallationId int64                  `protobuf:"varint,1,opt,name=target_installation_id,json=targetInstallationId,proto3" json:"target_installation_id,omitempty"`
	// Unprefixed event name in the calling plugin's namespace.
	EventName string `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Arbitrary JSON-shaped payload.
	Payload       *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventToInstallationRequest) Reset() {
	*x = PublishEventToInstallationRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventToInstallationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventToInstallationRequest) ProtoMessage() {}

func (x *PublishEventToInstallationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventToInstallationRequest.ProtoReflect.Descriptor instead.
func (*PublishEventToInstallationRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{7}
}

func (x *PublishEventToInstallationRequest) GetTargetInstallationId() int64 {
	if x != nil {
		return x.TargetInstallationId
	}
	return 0
}

func (x *PublishEventToInstallationRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PublishEventToInstallationRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishEventToInstallationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventToInstallationResponse) Reset() {
	*x = PublishEventToInstallationResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventToInstallationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventToInstallationResponse) ProtoMessage() {}

func (x *PublishEventToInstallationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventToInstallationResponse.ProtoReflect.Descriptor instead.
func (*PublishEventToInstallationResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{8}
}

type GetHostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostInfoRequest) Reset() {
	*x = GetHostInfoRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoRequest) ProtoMessage() {}

func (x *GetHostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoRequest.ProtoReflect.Descriptor instead.
func (*GetHostInfoRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{9}
}

type GetHostInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PublicBaseUrl      string                 `protobuf:"bytes,1,opt,name=public_base_url,json=publicBaseUrl,proto3" json:"public_base_url,omitempty"`
	InternalBaseUrl    string                 `protobuf:"bytes,2,opt,name=internal_base_url,json=internalBaseUrl,proto3" json:"internal_base_url,omitempty"`
	PluginProxyBaseUrl string                 `protobuf:"bytes,3,opt,name=plugin_proxy_base_url,json=pluginProxyBaseUrl,proto3" json:"plugin_proxy_base_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHostInfoResponse) Reset() {
	*x = GetHostInfoResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoResponse) ProtoMessage() {}

func (x *GetHostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoResponse.ProtoReflect.Descriptor instead.
func (*GetHostInfoResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{10}
}

func (x *GetHostInfoResponse) GetPublicBaseUrl() string {
	if x != nil {
		return x.PublicBaseUrl
	}
	return ""
}

func (x *GetHostInfoResponse) GetInternalBaseUrl() string {
	if x != nil {
		return x.InternalBaseUrl
	}
	return ""
}

func (x *GetHostInfoResponse) GetPluginProxyBaseUrl() string {
	if x != nil {
		return x.PluginProxyBaseUrl
	}
	return ""
}

type ListLibrariesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: scope results to libraries this user is allowed to see.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLibrariesRequest) Reset() {
	*x = ListLibrariesRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLibrariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibrariesRequest) ProtoMessage() {}

func (x *ListLibrariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibrariesRequest.ProtoReflect.Descriptor instead.
func (*ListLibrariesRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{11}
}

func (x *ListLibrariesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListLibrariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Libraries     []*Library             `protobuf:"bytes,1,rep,name=libraries,proto3" json:"libraries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLibrariesResponse) Reset() {
	*x = ListLibrariesResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLibrariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibrariesResponse) ProtoMessage() {}

func (x *ListLibrariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibrariesResponse.ProtoReflect.Descriptor instead.
func (*ListLibrariesResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{12}
}

func (x *ListLibrariesResponse) GetLibraries() []*Library {
	if x != nil {
		return x.Libraries
	}
	return nil
}

type Library struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// One of: "movie", "tv", "mixed".
	MediaType     string `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Library) Reset() {
	*x = Library{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Library) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Library) ProtoMessage() {}

func (x *Library) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Library.ProtoReflect.Descriptor instead.
func (*Library) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{13}
}

func (x *Library) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Library) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Library) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type CheckMediaPresenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// External provider identifier. Only "tmdb" is supported in v1.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// One of: "movie", "tv". Use "mixed" only for Library.media_type.
	MediaType string `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// External IDs to check. Capped at 100 per call (server returns
	// InvalidArgument otherwise).
	Ids           []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMediaPresenceRequest) Reset() {
	*x = CheckMediaPresenceRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMediaPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMediaPresenceRequest) ProtoMessage() {}

func (x *CheckMediaPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMediaPresenceRequest.ProtoReflect.Descriptor instead.
func (*CheckMediaPresenceRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{14}
}

func (x *CheckMediaPresenceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CheckMediaPresenceRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CheckMediaPresenceRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CheckMediaPresenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per ID that was found. IDs absent from this list are not
	// present in the host catalog.
	Present       []*MediaPresence `protobuf:"bytes,1,rep,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMediaPresenceResponse) Reset() {
	*x = CheckMediaPresenceResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMediaPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMediaPresenceResponse) ProtoMessage() {}

func (x *CheckMediaPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMediaPresenceResponse.ProtoReflect.Descriptor instead.
func (*CheckMediaPresenceResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{15}
}

func (x *CheckMediaPresenceResponse) GetPresent() []*MediaPresence {
	if x != nil {
		return x.Present
	}
	return nil
}

type MediaPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	LibraryId     string                 `protobuf:"bytes,3,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaPresence) Reset() {
	*x = MediaPresence{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaPresence) ProtoMessage() {}

func (x *MediaPresence) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaPresence.ProtoReflect.Descriptor instead.
func (*MediaPresence) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{16}
}

func (x *MediaPresence) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *MediaPresence) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaPresence) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *MediaPresence) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListInstalledPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstalledPluginsRequest) Reset() {
	*x = ListInstalledPluginsRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstalledPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstalledPluginsRequest) ProtoMessage() {}

func (x *ListInstalledPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstalledPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListInstalledPluginsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{17}
}

type ListInstalledPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*InstalledPlugin     `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstalledPluginsResponse) Reset() {
	*x = ListInstalledPluginsResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstalledPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstalledPluginsResponse) ProtoMessage() {}

func (x *ListInstalledPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstalledPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListInstalledPluginsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{18}
}

func (x *ListInstalledPluginsResponse) GetPlugins() []*InstalledPlugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type InstalledPlugin struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	InstallationId int64                   `protobuf:"varint,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	PluginId       string                  `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version        string                  `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Enabled        bool                    `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Capabilities   []*CapabilityDescriptor `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstalledPlugin) Reset() {
	*x = InstalledPlugin{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPlugin) ProtoMessage() {}

func (x *InstalledPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPlugin.ProtoReflect.Descriptor instead.
func (*InstalledPlugin) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{19}
}

func (x *InstalledPlugin) GetInstallationId() int64 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *InstalledPlugin) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *InstalledPlugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPlugin) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *InstalledPlugin) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SetGlobalConfigEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalConfigEntryRequest) Reset() {
	*x = SetGlobalConfigEntryRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalConfigEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalConfigEntryRequest) ProtoMessage() {}

func (x *SetGlobalConfigEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalConfigEntryRequest.ProtoReflect.Descriptor instead.
func (*SetGlobalConfigEntryRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{20}
}

func (x *SetGlobalConfigEntryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetGlobalConfigEntryRequest) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetGlobalConfigEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalConfigEntryResponse) Reset() {
	*x = SetGlobalConfigEntryResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalConfigEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalConfigEntryResponse) ProtoMessage() {}

func (x *SetGlobalConfigEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalConfigEntryResponse.ProtoReflect.Descriptor instead.
func (*SetGlobalConfigEntryResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{21}
}

type ListLibraryMediaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means all libraries visible to the plugin/host policy.
	LibraryIds []string `protobuf:"bytes,1,rep,name=library_ids,json=libraryIds,proto3" json:"library_ids,omitempty"`
	// Empty means all supported media types.
	MediaTypes []string `protobuf:"bytes,2,rep,name=media_types,json=mediaTypes,proto3" json:"media_types,omitempty"`
	Query      string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Genre      string   `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	YearMin    int32    `protobuf:"varint,5,opt,name=year_min,json=yearMin,proto3" json:"year_min,omitempty"`
	YearMax    int32    `protobuf:"varint,6,opt,name=year_max,json=yearMax,proto3" json:"year_max,omitempty"`
	// Stable sort keys: "title", "year", "added_at", "runtime", "rating".
	Sort          string `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	Descending    bool   `protobuf:"varint,8,opt,name=descending,proto3" json:"descending,omitempty"`
	PageSize      int32  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLibraryMediaRequest) Reset() {
	*x = ListLibraryMediaRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLibraryMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibraryMediaRequest) ProtoMessage() {}

func (x *ListLibraryMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibraryMediaRequest.ProtoReflect.Descriptor instead.
func (*ListLibraryMediaRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{22}
}

func (x *ListLibraryMediaRequest) GetLibraryIds() []string {
	if x != nil {
		return x.LibraryIds
	}
	return nil
}

func (x *ListLibraryMediaRequest) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

func (x *ListLibraryMediaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListLibraryMediaRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ListLibraryMediaRequest) GetYearMin() int32 {
	if x != nil {
		return x.YearMin
	}
	return 0
}

func (x *ListLibraryMediaRequest) GetYearMax() int32 {
	if x != nil {
		return x.YearMax
	}
	return 0
}

func (x *ListLibraryMediaRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListLibraryMediaRequest) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

func (x *ListLibraryMediaRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLibraryMediaRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLibraryMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogMediaItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLibraryMediaResponse) Reset() {
	*x = ListLibraryMediaResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLibraryMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibraryMediaResponse) ProtoMessage() {}

func (x *ListLibraryMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibraryMediaResponse.ProtoReflect.Descriptor instead.
func (*ListLibraryMediaResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{23}
}

func (x *ListLibraryMediaResponse) GetItems() []*CatalogMediaItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLibraryMediaResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListLibraryMediaResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CatalogMediaItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MediaId          string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	LibraryId        string                 `protobuf:"bytes,2,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	MediaType        string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Year             int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Overview         string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterUrl        string                 `protobuf:"bytes,7,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	BackdropUrl      string                 `protobuf:"bytes,8,opt,name=backdrop_url,json=backdropUrl,proto3" json:"backdrop_url,omitempty"`
	Genres           []string               `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	RuntimeMinutes   int32                  `protobuf:"varint,10,opt,name=runtime_minutes,json=runtimeMinutes,proto3" json:"runtime_minutes,omitempty"`
	Rating           float64                `protobuf:"fixed64,11,opt,name=rating,proto3" json:"rating,omitempty"`
	ContentRating    string                 `protobuf:"bytes,12,opt,name=content_rating,json=contentRating,proto3" json:"content_rating,omitempty"`
	AddedAt          string                 `protobuf:"bytes,13,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	ExternalProvider string                 `protobuf:"bytes,14,opt,name=external_provider,json=externalProvider,proto3" json:"external_provider,omitempty"`
	ExternalId       string                 `protobuf:"bytes,15,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatalogMediaItem) Reset() {
	*x = CatalogMediaItem{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogMediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogMediaItem) ProtoMessage() {}

func (x *CatalogMediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogMediaItem.ProtoReflect.Descriptor instead.
func (*CatalogMediaItem) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{24}
}

func (x *CatalogMediaItem) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CatalogMediaItem) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *CatalogMediaItem) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CatalogMediaItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CatalogMediaItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CatalogMediaItem) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *CatalogMediaItem) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *CatalogMediaItem) GetBackdropUrl() string {
	if x != nil {
		return x.BackdropUrl
	}
	return ""
}

func (x *CatalogMediaItem) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *CatalogMediaItem) GetRuntimeMinutes() int32 {
	if x != nil {
		return x.RuntimeMinutes
	}
	return 0
}

func (x *CatalogMediaItem) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CatalogMediaItem) GetContentRating() string {
	if x != nil {
		return x.ContentRating
	}
	return ""
}

func (x *CatalogMediaItem) GetAddedAt() string {
	if x != nil {
		return x.AddedAt
	}
	return ""
}

func (x *CatalogMediaItem) GetExternalProvider() string {
	if x != nil {
		return x.ExternalProvider
	}
	return ""
}

func (x *CatalogMediaItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type GetCatalogStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means all libraries visible to the plugin/host policy.
	LibraryIds    []string `protobuf:"bytes,1,rep,name=library_ids,json=libraryIds,proto3" json:"library_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogStatsRequest) Reset() {
	*x = GetCatalogStatsRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogStatsRequest) ProtoMessage() {}

func (x *GetCatalogStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogStatsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{25}
}

func (x *GetCatalogStatsRequest) GetLibraryIds() []string {
	if x != nil {
		return x.LibraryIds
	}
	return nil
}

type GetCatalogStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalItems      int32                  `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	MediaTypeCounts []*CatalogTypeCount    `protobuf:"bytes,2,rep,name=media_type_counts,json=mediaTypeCounts,proto3" json:"media_type_counts,omitempty"`
	LibraryCounts   []*CatalogLibraryCount `protobuf:"bytes,3,rep,name=library_counts,json=libraryCounts,proto3" json:"library_counts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCatalogStatsResponse) Reset() {
	*x = GetCatalogStatsResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogStatsResponse) ProtoMessage() {}

func (x *GetCatalogStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogStatsResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogStatsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{26}
}

func (x *GetCatalogStatsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *GetCatalogStatsResponse) GetMediaTypeCounts() []*CatalogTypeCount {
	if x != nil {
		return x.MediaTypeCounts
	}
	return nil
}

func (x *GetCatalogStatsResponse) GetLibraryCounts() []*CatalogLibraryCount {
	if x != nil {
		return x.LibraryCounts
	}
	return nil
}

type CatalogTypeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogTypeCount) Reset() {
	*x = CatalogTypeCount{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogTypeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogTypeCount) ProtoMessage() {}

func (x *CatalogTypeCount) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogTypeCount.ProtoReflect.Descriptor instead.
func (*CatalogTypeCount) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{27}
}

func (x *CatalogTypeCount) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CatalogTypeCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CatalogLibraryCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LibraryId     string                 `protobuf:"bytes,1,opt,name=library_id,json=libraryId,proto3" json:"library_id,omitempty"`
	LibraryName   string                 `protobuf:"bytes,2,opt,name=library_name,json=libraryName,proto3" json:"library_name,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogLibraryCount) Reset() {
	*x = CatalogLibraryCount{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogLibraryCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogLibraryCount) ProtoMessage() {}

func (x *CatalogLibraryCount) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogLibraryCount.ProtoReflect.Descriptor instead.
func (*CatalogLibraryCount) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{28}
}

func (x *CatalogLibraryCount) GetLibraryId() string {
	if x != nil {
		return x.LibraryId
	}
	return ""
}

func (x *CatalogLibraryCount) GetLibraryName() string {
	if x != nil {
		return x.LibraryName
	}
	return ""
}

func (x *CatalogLibraryCount) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CatalogLibraryCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ResolveCatalogImageURLsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stored catalog image paths from catalog metadata, such as poster_url or
	// backdrop_url values returned by ListLibraryMedia. Paths are host-owned
	// opaque strings; plugins should pass them back unchanged.
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	// Optional image variant name understood by the host resolver. Empty uses the
	// host default. Common values include "thumbnail" and "original"; unsupported
	// variants are handled host-side.
	Variant       string `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCatalogImageURLsRequest) Reset() {
	*x = ResolveCatalogImageURLsRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCatalogImageURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCatalogImageURLsRequest) ProtoMessage() {}

func (x *ResolveCatalogImageURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCatalogImageURLsRequest.ProtoReflect.Descriptor instead.
func (*ResolveCatalogImageURLsRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{29}
}

func (x *ResolveCatalogImageURLsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ResolveCatalogImageURLsRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type ResolveCatalogImageURLsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Browser-usable URLs keyed by the original input path. Paths that cannot be
	// resolved are omitted. URLs are host-generated browser targets and should be
	// treated as opaque by plugins.
	Urls          map[string]string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCatalogImageURLsResponse) Reset() {
	*x = ResolveCatalogImageURLsResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCatalogImageURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCatalogImageURLsResponse) ProtoMessage() {}

func (x *ResolveCatalogImageURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCatalogImageURLsResponse.ProtoReflect.Descriptor instead.
func (*ResolveCatalogImageURLsResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{30}
}

func (x *ResolveCatalogImageURLsResponse) GetUrls() map[string]string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type MintScopedStreamRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MediaFileId         int64                  `protobuf:"varint,1,opt,name=media_file_id,json=mediaFileId,proto3" json:"media_file_id,omitempty"`
	PlayMethod          string                 `protobuf:"bytes,2,opt,name=play_method,json=playMethod,proto3" json:"play_method,omitempty"` // "direct" or "remux"; "auto" chooses from policy.
	ExpiresAtUnix       int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	MaxWatchMinutes     int32                  `protobuf:"varint,4,opt,name=max_watch_minutes,json=maxWatchMinutes,proto3" json:"max_watch_minutes,omitempty"`
	MaxResolutionHeight int32                  `protobuf:"varint,5,opt,name=max_resolution_height,json=maxResolutionHeight,proto3" json:"max_resolution_height,omitempty"`
	AllowDirectPlay     bool                   `protobuf:"varint,6,opt,name=allow_direct_play,json=allowDirectPlay,proto3" json:"allow_direct_play,omitempty"`
	AllowDownloads      bool                   `protobuf:"varint,7,opt,name=allow_downloads,json=allowDownloads,proto3" json:"allow_downloads,omitempty"`
	DisableSeeking      bool                   `protobuf:"varint,8,opt,name=disable_seeking,json=disableSeeking,proto3" json:"disable_seeking,omitempty"`
	AuditSubject        string                 `protobuf:"bytes,9,opt,name=audit_subject,json=auditSubject,proto3" json:"audit_subject,omitempty"`
	WatermarkMode       string                 `protobuf:"bytes,10,opt,name=watermark_mode,json=watermarkMode,proto3" json:"watermark_mode,omitempty"`
	WatermarkText       string                 `protobuf:"bytes,11,opt,name=watermark_text,json=watermarkText,proto3" json:"watermark_text,omitempty"`
	WatermarkLogoUrl    string                 `protobuf:"bytes,12,opt,name=watermark_logo_url,json=watermarkLogoUrl,proto3" json:"watermark_logo_url,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MintScopedStreamRequest) Reset() {
	*x = MintScopedStreamRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintScopedStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintScopedStreamRequest) ProtoMessage() {}

func (x *MintScopedStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintScopedStreamRequest.ProtoReflect.Descriptor instead.
func (*MintScopedStreamRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{31}
}

func (x *MintScopedStreamRequest) GetMediaFileId() int64 {
	if x != nil {
		return x.MediaFileId
	}
	return 0
}

func (x *MintScopedStreamRequest) GetPlayMethod() string {
	if x != nil {
		return x.PlayMethod
	}
	return ""
}

func (x *MintScopedStreamRequest) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *MintScopedStreamRequest) GetMaxWatchMinutes() int32 {
	if x != nil {
		return x.MaxWatchMinutes
	}
	return 0
}

func (x *MintScopedStreamRequest) GetMaxResolutionHeight() int32 {
	if x != nil {
		return x.MaxResolutionHeight
	}
	return 0
}

func (x *MintScopedStreamRequest) GetAllowDirectPlay() bool {
	if x != nil {
		return x.AllowDirectPlay
	}
	return false
}

func (x *MintScopedStreamRequest) GetAllowDownloads() bool {
	if x != nil {
		return x.AllowDownloads
	}
	return false
}

func (x *MintScopedStreamRequest) GetDisableSeeking() bool {
	if x != nil {
		return x.DisableSeeking
	}
	return false
}

func (x *MintScopedStreamRequest) GetAuditSubject() string {
	if x != nil {
		return x.AuditSubject
	}
	return ""
}

func (x *MintScopedStreamRequest) GetWatermarkMode() string {
	if x != nil {
		return x.WatermarkMode
	}
	return ""
}

func (x *MintScopedStreamRequest) GetWatermarkText() string {
	if x != nil {
		return x.WatermarkText
	}
	return ""
}

func (x *MintScopedStreamRequest) GetWatermarkLogoUrl() string {
	if x != nil {
		return x.WatermarkLogoUrl
	}
	return ""
}

type MintScopedStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	PlayMethod    string                 `protobuf:"bytes,2,opt,name=play_method,json=playMethod,proto3" json:"play_method,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintScopedStreamResponse) Reset() {
	*x = MintScopedStreamResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintScopedStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintScopedStreamResponse) ProtoMessage() {}

func (x *MintScopedStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintScopedStreamResponse.ProtoReflect.Descriptor instead.
func (*MintScopedStreamResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{32}
}

func (x *MintScopedStreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *MintScopedStreamResponse) GetPlayMethod() string {
	if x != nil {
		return x.PlayMethod
	}
	return ""
}

func (x *MintScopedStreamResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CallPluginHTTPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallationId int32                  `protobuf:"varint,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path           string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Query          *structpb.Struct       `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallPluginHTTPRequest) Reset() {
	*x = CallPluginHTTPRequest{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginHTTPRequest) ProtoMessage() {}

func (x *CallPluginHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginHTTPRequest.ProtoReflect.Descriptor instead.
func (*CallPluginHTTPRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{33}
}

func (x *CallPluginHTTPRequest) GetInstallationId() int32 {
	if x != nil {
		return x.InstallationId
	}
	return 0
}

func (x *CallPluginHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallPluginHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallPluginHTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallPluginHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CallPluginHTTPRequest) GetQuery() *structpb.Struct {
	if x != nil {
		return x.Query
	}
	return nil
}

type CallPluginHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPluginHTTPResponse) Reset() {
	*x = CallPluginHTTPResponse{}
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPluginHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPluginHTTPResponse) ProtoMessage() {}

func (x *CallPluginHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_runtime_host_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPluginHTTPResponse.ProtoReflect.Descriptor instead.
func (*CallPluginHTTPResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_runtime_host_proto_rawDescGZIP(), []int{34}
}

func (x *CallPluginHTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CallPluginHTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallPluginHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_silo_plugin_v1_runtime_host_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_runtime_host_proto_rawDesc = "" +
	"\n" +
	"!silo/plugin/v1/runtime_host.proto\x12\x0esilo.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bsilo/plugin/v1/common.proto\"\xce\x03\n" +
	"\x19UpsertVirtualMediaRequest\x12\x1d\n" +
	"\n" +
	"library_id\x18\x01 \x01(\tR\tlibraryId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x17\n" +
	"\aimdb_id\x18\x05 \x01(\tR\x06imdbId\x12\x17\n" +
	"\atmdb_id\x18\x06 \x01(\tR\x06tmdbId\x12\x17\n" +
	"\atvdb_id\x18\a \x01(\tR\x06tvdbId\x12\x1a\n" +
	"\boverview\x18\b \x01(\tR\boverview\x12\x16\n" +
	"\x06genres\x18\t \x03(\tR\x06genres\x12\x1f\n" +
	"\vposter_path\x18\n" +
	" \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\v \x01(\tR\fbackdropPath\x12\x1f\n" +
	"\vvirtual_uri\x18\f \x01(\tR\n" +
	"virtualUri\x12:\n" +
	"\bepisodes\x18\r \x03(\v2\x1e.silo.plugin.v1.VirtualEpisodeR\bepisodes\x12'\n" +
	"\x0fruntime_minutes\x18\x0e \x01(\x05R\x0eruntimeMinutes\"\x9b\x02\n" +
	"\x0eVirtualEpisode\x12#\n" +
	"\rseason_number\x18\x01 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\x02 \x01(\x05R\repisodeNumber\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\"\n" +
	"\rair_date_unix\x18\x05 \x01(\x03R\vairDateUnix\x12'\n" +
	"\x0fruntime_minutes\x18\x06 \x01(\x05R\x0eruntimeMinutes\x12\x1d\n" +
	"\n" +
	"still_path\x18\a \x01(\tR\tstillPath\x12\x1f\n" +
	"\vvirtual_uri\x18\b \x01(\tR\n" +
	"virtualUri\"\x83\x01\n" +
	"\x1aUpsertVirtualMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x01(\tR\tlibraryId\x12+\n" +
	"\x11episodes_upserted\x18\x03 \x01(\x05R\x10episodesUpserted\"g\n" +
	"\x13PublishEventRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x16\n" +
	"\x14PublishEventResponse\"\x93\x01\n" +
	"\x15PublishEventToRequest\x12(\n" +
	"\x10target_plugin_id\x18\x01 \x01(\tR\x0etargetPluginId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x18\n" +
	"\x16PublishEventToResponse\"\xab\x01\n" +
	"!PublishEventToInstallationRequest\x124\n" +
	"\x16target_installation_id\x18\x01 \x01(\x03R\x14targetInstallationId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"$\n" +
	"\"PublishEventToInstallationResponse\"\x14\n" +
	"\x12GetHostInfoRequest\"\x9c\x01\n" +
	"\x13GetHostInfoResponse\x12&\n" +
	"\x0fpublic_base_url\x18\x01 \x01(\tR\rpublicBaseUrl\x12*\n" +
	"\x11internal_base_url\x18\x02 \x01(\tR\x0finternalBaseUrl\x121\n" +
	"\x15plugin_proxy_base_url\x18\x03 \x01(\tR\x12pluginProxyBaseUrl\"/\n" +
	"\x14ListLibrariesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x15ListLibrariesResponse\x125\n" +
	"\tlibraries\x18\x01 \x03(\v2\x17.silo.plugin.v1.LibraryR\tlibraries\"L\n" +
	"\aLibrary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\"h\n" +
	"\x19CheckMediaPresenceRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\tR\x03ids\"U\n" +
	"\x1aCheckMediaPresenceResponse\x127\n" +
	"\apresent\x18\x01 \x03(\v2\x1d.silo.plugin.v1.MediaPresenceR\apresent\"\x80\x01\n" +
	"\rMediaPresence\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x03 \x01(\tR\tlibraryId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\x1d\n" +
	"\x1bListInstalledPluginsRequest\"Y\n" +
	"\x1cListInstalledPluginsResponse\x129\n" +
	"\aplugins\x18\x01 \x03(\v2\x1f.silo.plugin.v1.InstalledPluginR\aplugins\"\xd5\x01\n" +
	"\x0fInstalledPlugin\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\x03R\x0einstallationId\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12H\n" +
	"\fcapabilities\x18\x05 \x03(\v2$.silo.plugin.v1.CapabilityDescriptorR\fcapabilities\"^\n" +
	"\x1bSetGlobalConfigEntryRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"\x1e\n" +
	"\x1cSetGlobalConfigEntryResponse\"\xad\x02\n" +
	"\x17ListLibraryMediaRequest\x12\x1f\n" +
	"\vlibrary_ids\x18\x01 \x03(\tR\n" +
	"libraryIds\x12\x1f\n" +
	"\vmedia_types\x18\x02 \x03(\tR\n" +
	"mediaTypes\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\x12\x19\n" +
	"\byear_min\x18\x05 \x01(\x05R\ayearMin\x12\x19\n" +
	"\byear_max\x18\x06 \x01(\x05R\ayearMax\x12\x12\n" +
	"\x04sort\x18\a \x01(\tR\x04sort\x12\x1e\n" +
	"\n" +
	"descending\x18\b \x01(\bR\n" +
	"descending\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tR\tpageToken\"\x9b\x01\n" +
	"\x18ListLibraryMediaResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .silo.plugin.v1.CatalogMediaItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xdc\x03\n" +
	"\x10CatalogMediaItem\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"library_id\x18\x02 \x01(\tR\tlibraryId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12\x1d\n" +
	"\n" +
	"poster_url\x18\a \x01(\tR\tposterUrl\x12!\n" +
	"\fbackdrop_url\x18\b \x01(\tR\vbackdropUrl\x12\x16\n" +
	"\x06genres\x18\t \x03(\tR\x06genres\x12'\n" +
	"\x0fruntime_minutes\x18\n" +
	" \x01(\x05R\x0eruntimeMinutes\x12\x16\n" +
	"\x06rating\x18\v \x01(\x01R\x06rating\x12%\n" +
	"\x0econtent_rating\x18\f \x01(\tR\rcontentRating\x12\x19\n" +
	"\badded_at\x18\r \x01(\tR\aaddedAt\x12+\n" +
	"\x11external_provider\x18\x0e \x01(\tR\x10externalProvider\x12\x1f\n" +
	"\vexternal_id\x18\x0f \x01(\tR\n" +
	"externalId\"9\n" +
	"\x16GetCatalogStatsRequest\x12\x1f\n" +
	"\vlibrary_ids\x18\x01 \x03(\tR\n" +
	"libraryIds\"\xd4\x01\n" +
	"\x17GetCatalogStatsResponse\x12\x1f\n" +
	"\vtotal_items\x18\x01 \x01(\x05R\n" +
	"totalItems\x12L\n" +
	"\x11media_type_counts\x18\x02 \x03(\v2 .silo.plugin.v1.CatalogTypeCountR\x0fmediaTypeCounts\x12J\n" +
	"\x0elibrary_counts\x18\x03 \x03(\v2#.silo.plugin.v1.CatalogLibraryCountR\rlibraryCounts\"G\n" +
	"\x10CatalogTypeCount\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x8c\x01\n" +
	"\x13CatalogLibraryCount\x12\x1d\n" +
	"\n" +
	"library_id\x18\x01 \x01(\tR\tlibraryId\x12!\n" +
	"\flibrary_name\x18\x02 \x01(\tR\vlibraryName\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"P\n" +
	"\x1eResolveCatalogImageURLsRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\"\xa9\x01\n" +
	"\x1fResolveCatalogImageURLsResponse\x12M\n" +
	"\x04urls\x18\x01 \x03(\v29.silo.plugin.v1.ResolveCatalogImageURLsResponse.UrlsEntryR\x04urls\x1a7\n" +
	"\tUrlsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x04\n" +
	"\x17MintScopedStreamRequest\x12\"\n" +
	"\rmedia_file_id\x18\x01 \x01(\x03R\vmediaFileId\x12\x1f\n" +
	"\vplay_method\x18\x02 \x01(\tR\n" +
	"playMethod\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12*\n" +
	"\x11max_watch_minutes\x18\x04 \x01(\x05R\x0fmaxWatchMinutes\x122\n" +
	"\x15max_resolution_height\x18\x05 \x01(\x05R\x13maxResolutionHeight\x12*\n" +
	"\x11allow_direct_play\x18\x06 \x01(\bR\x0fallowDirectPlay\x12'\n" +
	"\x0fallow_downloads\x18\a \x01(\bR\x0eallowDownloads\x12'\n" +
	"\x0fdisable_seeking\x18\b \x01(\bR\x0edisableSeeking\x12#\n" +
	"\raudit_subject\x18\t \x01(\tR\fauditSubject\x12%\n" +
	"\x0ewatermark_mode\x18\n" +
	" \x01(\tR\rwatermarkMode\x12%\n" +
	"\x0ewatermark_text\x18\v \x01(\tR\rwatermarkText\x12,\n" +
	"\x12watermark_logo_url\x18\f \x01(\tR\x10watermarkLogoUrl\"\x82\x01\n" +
	"\x18MintScopedStreamResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12\x1f\n" +
	"\vplay_method\x18\x02 \x01(\tR\n" +
	"playMethod\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\"\xb9\x02\n" +
	"\x15CallPluginHTTPRequest\x12'\n" +
	"\x0finstallation_id\x18\x01 \x01(\x05R\x0einstallationId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12L\n" +
	"\aheaders\x18\x04 \x03(\v22.silo.plugin.v1.CallPluginHTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12-\n" +
	"\x05query\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x05query\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x16CallPluginHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12M\n" +
	"\aheaders\x18\x02 \x03(\v23.silo.plugin.v1.CallPluginHTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd4\v\n" +
	"\vRuntimeHost\x12Y\n" +
	"\fPublishEvent\x12#.silo.plugin.v1.PublishEventRequest\x1a$.silo.plugin.v1.PublishEventResponse\x12_\n" +
	"\x0ePublishEventTo\x12%.silo.plugin.v1.PublishEventToRequest\x1a&.silo.plugin.v1.PublishEventToResponse\x12\x83\x01\n" +
	"\x1aPublishEventToInstallation\x121.silo.plugin.v1.PublishEventToInstallationRequest\x1a2.silo.plugin.v1.PublishEventToInstallationResponse\x12V\n" +
	"\vGetHostInfo\x12\".silo.plugin.v1.GetHostInfoRequest\x1a#.silo.plugin.v1.GetHostInfoResponse\x12\\\n" +
	"\rListLibraries\x12$.silo.plugin.v1.ListLibrariesRequest\x1a%.silo.plugin.v1.ListLibrariesResponse\x12k\n" +
	"\x12CheckMediaPresence\x12).silo.plugin.v1.CheckMediaPresenceRequest\x1a*.silo.plugin.v1.CheckMediaPresenceResponse\x12q\n" +
	"\x14ListInstalledPlugins\x12+.silo.plugin.v1.ListInstalledPluginsRequest\x1a,.silo.plugin.v1.ListInstalledPluginsResponse\x12q\n" +
	"\x14SetGlobalConfigEntry\x12+.silo.plugin.v1.SetGlobalConfigEntryRequest\x1a,.silo.plugin.v1.SetGlobalConfigEntryResponse\x12e\n" +
	"\x10ListLibraryMedia\x12'.silo.plugin.v1.ListLibraryMediaRequest\x1a(.silo.plugin.v1.ListLibraryMediaResponse\x12b\n" +
	"\x0fGetCatalogStats\x12&.silo.plugin.v1.GetCatalogStatsRequest\x1a'.silo.plugin.v1.GetCatalogStatsResponse\x12z\n" +
	"\x17ResolveCatalogImageURLs\x12..silo.plugin.v1.ResolveCatalogImageURLsRequest\x1a/.silo.plugin.v1.ResolveCatalogImageURLsResponse\x12e\n" +
	"\x10MintScopedStream\x12'.silo.plugin.v1.MintScopedStreamRequest\x1a(.silo.plugin.v1.MintScopedStreamResponse\x12_\n" +
	"\x0eCallPluginHTTP\x12%.silo.plugin.v1.CallPluginHTTPRequest\x1a&.silo.plugin.v1.CallPluginHTTPResponse\x12k\n" +
	"\x12UpsertVirtualMedia\x12).silo.plugin.v1.UpsertVirtualMediaRequest\x1a*.silo.plugin.v1.UpsertVirtualMediaResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_runtime_host_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_runtime_host_proto_rawDescData []byte
)

func file_silo_plugin_v1_runtime_host_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_runtime_host_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_runtime_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_runtime_host_proto_rawDesc), len(file_silo_plugin_v1_runtime_host_proto_rawDesc)))
	})
	return file_silo_plugin_v1_runtime_host_proto_rawDescData
}

var file_silo_plugin_v1_runtime_host_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_silo_plugin_v1_runtime_host_proto_goTypes = []any{
	(*UpsertVirtualMediaRequest)(nil),          // 0: silo.plugin.v1.UpsertVirtualMediaRequest
	(*VirtualEpisode)(nil),                     // 1: silo.plugin.v1.VirtualEpisode
	(*UpsertVirtualMediaResponse)(nil),         // 2: silo.plugin.v1.UpsertVirtualMediaResponse
	(*PublishEventRequest)(nil),                // 3: silo.plugin.v1.PublishEventRequest
	(*PublishEventResponse)(nil),               // 4: silo.plugin.v1.PublishEventResponse
	(*PublishEventToRequest)(nil),              // 5: silo.plugin.v1.PublishEventToRequest
	(*PublishEventToResponse)(nil),             // 6: silo.plugin.v1.PublishEventToResponse
	(*PublishEventToInstallationRequest)(nil),  // 7: silo.plugin.v1.PublishEventToInstallationRequest
	(*PublishEventToInstallationResponse)(nil), // 8: silo.plugin.v1.PublishEventToInstallationResponse
	(*GetHostInfoRequest)(nil),                 // 9: silo.plugin.v1.GetHostInfoRequest
	(*GetHostInfoResponse)(nil),                // 10: silo.plugin.v1.GetHostInfoResponse
	(*ListLibrariesRequest)(nil),               // 11: silo.plugin.v1.ListLibrariesRequest
	(*ListLibrariesResponse)(nil),              // 12: silo.plugin.v1.ListLibrariesResponse
	(*Library)(nil),                            // 13: silo.plugin.v1.Library
	(*CheckMediaPresenceRequest)(nil),          // 14: silo.plugin.v1.CheckMediaPresenceRequest
	(*CheckMediaPresenceResponse)(nil),         // 15: silo.plugin.v1.CheckMediaPresenceResponse
	(*MediaPresence)(nil),                      // 16: silo.plugin.v1.MediaPresence
	(*ListInstalledPluginsRequest)(nil),        // 17: silo.plugin.v1.ListInstalledPluginsRequest
	(*ListInstalledPluginsResponse)(nil),       // 18: silo.plugin.v1.ListInstalledPluginsResponse
	(*InstalledPlugin)(nil),                    // 19: silo.plugin.v1.InstalledPlugin
	(*SetGlobalConfigEntryRequest)(nil),        // 20: silo.plugin.v1.SetGlobalConfigEntryRequest
	(*SetGlobalConfigEntryResponse)(nil),       // 21: silo.plugin.v1.SetGlobalConfigEntryResponse
	(*ListLibraryMediaRequest)(nil),            // 22: silo.plugin.v1.ListLibraryMediaRequest
	(*ListLibraryMediaResponse)(nil),           // 23: silo.plugin.v1.ListLibraryMediaResponse
	(*CatalogMediaItem)(nil),                   // 24: silo.plugin.v1.CatalogMediaItem
	(*GetCatalogStatsRequest)(nil),             // 25: silo.plugin.v1.GetCatalogStatsRequest
	(*GetCatalogStatsResponse)(nil),            // 26: silo.plugin.v1.GetCatalogStatsResponse
	(*CatalogTypeCount)(nil),                   // 27: silo.plugin.v1.CatalogTypeCount
	(*CatalogLibraryCount)(nil),                // 28: silo.plugin.v1.CatalogLibraryCount
	(*ResolveCatalogImageURLsRequest)(nil),     // 29: silo.plugin.v1.ResolveCatalogImageURLsRequest
	(*ResolveCatalogImageURLsResponse)(nil),    // 30: silo.plugin.v1.ResolveCatalogImageURLsResponse
	(*MintScopedStreamRequest)(nil),            // 31: silo.plugin.v1.MintScopedStreamRequest
	(*MintScopedStreamResponse)(nil),           // 32: silo.plugin.v1.MintScopedStreamResponse
	(*CallPluginHTTPRequest)(nil),              // 33: silo.plugin.v1.CallPluginHTTPRequest
	(*CallPluginHTTPResponse)(nil),             // 34: silo.plugin.v1.CallPluginHTTPResponse
	nil,                                        // 35: silo.plugin.v1.ResolveCatalogImageURLsResponse.UrlsEntry
	nil,                                        // 36: silo.plugin.v1.CallPluginHTTPRequest.HeadersEntry
	nil,                                        // 37: silo.plugin.v1.CallPluginHTTPResponse.HeadersEntry
	(*structpb.Struct)(nil),                    // 38: google.protobuf.Struct
	(*CapabilityDescriptor)(nil),               // 39: silo.plugin.v1.CapabilityDescriptor
}
var file_silo_plugin_v1_runtime_host_proto_depIdxs = []int32{
	1,  // 0: silo.plugin.v1.UpsertVirtualMediaRequest.episodes:type_name -> silo.plugin.v1.VirtualEpisode
	38, // 1: silo.plugin.v1.PublishEventRequest.payload:type_name -> google.protobuf.Struct
	38, // 2: silo.plugin.v1.PublishEventToRequest.payload:type_name -> google.protobuf.Struct
	38, // 3: silo.plugin.v1.PublishEventToInstallationRequest.payload:type_name -> google.protobuf.Struct
	13, // 4: silo.plugin.v1.ListLibrariesResponse.libraries:type_name -> silo.plugin.v1.Library
	16, // 5: silo.plugin.v1.CheckMediaPresenceResponse.present:type_name -> silo.plugin.v1.MediaPresence
	19, // 6: silo.plugin.v1.ListInstalledPluginsResponse.plugins:type_name -> silo.plugin.v1.InstalledPlugin
	39, // 7: silo.plugin.v1.InstalledPlugin.capabilities:type_name -> silo.plugin.v1.CapabilityDescriptor
	38, // 8: silo.plugin.v1.SetGlobalConfigEntryRequest.value:type_name -> google.protobuf.Struct
	24, // 9: silo.plugin.v1.ListLibraryMediaResponse.items:type_name -> silo.plugin.v1.CatalogMediaItem
	27, // 10: silo.plugin.v1.GetCatalogStatsResponse.media_type_counts:type_name -> silo.plugin.v1.CatalogTypeCount
	28, // 11: silo.plugin.v1.GetCatalogStatsResponse.library_counts:type_name -> silo.plugin.v1.CatalogLibraryCount
	35, // 12: silo.plugin.v1.ResolveCatalogImageURLsResponse.urls:type_name -> silo.plugin.v1.ResolveCatalogImageURLsResponse.UrlsEntry
	36, // 13: silo.plugin.v1.CallPluginHTTPRequest.headers:type_name -> silo.plugin.v1.CallPluginHTTPRequest.HeadersEntry
	38, // 14: silo.plugin.v1.CallPluginHTTPRequest.query:type_name -> google.protobuf.Struct
	37, // 15: silo.plugin.v1.CallPluginHTTPResponse.headers:type_name -> silo.plugin.v1.CallPluginHTTPResponse.HeadersEntry
	3,  // 16: silo.plugin.v1.RuntimeHost.PublishEvent:input_type -> silo.plugin.v1.PublishEventRequest
	5,  // 17: silo.plugin.v1.RuntimeHost.PublishEventTo:input_type -> silo.plugin.v1.PublishEventToRequest
	7,  // 18: silo.plugin.v1.RuntimeHost.PublishEventToInstallation:input_type -> silo.plugin.v1.PublishEventToInstallationRequest
	9,  // 19: silo.plugin.v1.RuntimeHost.GetHostInfo:input_type -> silo.plugin.v1.GetHostInfoRequest
	11, // 20: silo.plugin.v1.RuntimeHost.ListLibraries:input_type -> silo.plugin.v1.ListLibrariesRequest
	14, // 21: silo.plugin.v1.RuntimeHost.CheckMediaPresence:input_type -> silo.plugin.v1.CheckMediaPresenceRequest
	17, // 22: silo.plugin.v1.RuntimeHost.ListInstalledPlugins:input_type -> silo.plugin.v1.ListInstalledPluginsRequest
	20, // 23: silo.plugin.v1.RuntimeHost.SetGlobalConfigEntry:input_type -> silo.plugin.v1.SetGlobalConfigEntryRequest
	22, // 24: silo.plugin.v1.RuntimeHost.ListLibraryMedia:input_type -> silo.plugin.v1.ListLibraryMediaRequest
	25, // 25: silo.plugin.v1.RuntimeHost.GetCatalogStats:input_type -> silo.plugin.v1.GetCatalogStatsRequest
	29, // 26: silo.plugin.v1.RuntimeHost.ResolveCatalogImageURLs:input_type -> silo.plugin.v1.ResolveCatalogImageURLsRequest
	31, // 27: silo.plugin.v1.RuntimeHost.MintScopedStream:input_type -> silo.plugin.v1.MintScopedStreamRequest
	33, // 28: silo.plugin.v1.RuntimeHost.CallPluginHTTP:input_type -> silo.plugin.v1.CallPluginHTTPRequest
	0,  // 29: silo.plugin.v1.RuntimeHost.UpsertVirtualMedia:input_type -> silo.plugin.v1.UpsertVirtualMediaRequest
	4,  // 30: silo.plugin.v1.RuntimeHost.PublishEvent:output_type -> silo.plugin.v1.PublishEventResponse
	6,  // 31: silo.plugin.v1.RuntimeHost.PublishEventTo:output_type -> silo.plugin.v1.PublishEventToResponse
	8,  // 32: silo.plugin.v1.RuntimeHost.PublishEventToInstallation:output_type -> silo.plugin.v1.PublishEventToInstallationResponse
	10, // 33: silo.plugin.v1.RuntimeHost.GetHostInfo:output_type -> silo.plugin.v1.GetHostInfoResponse
	12, // 34: silo.plugin.v1.RuntimeHost.ListLibraries:output_type -> silo.plugin.v1.ListLibrariesResponse
	15, // 35: silo.plugin.v1.RuntimeHost.CheckMediaPresence:output_type -> silo.plugin.v1.CheckMediaPresenceResponse
	18, // 36: silo.plugin.v1.RuntimeHost.ListInstalledPlugins:output_type -> silo.plugin.v1.ListInstalledPluginsResponse
	21, // 37: silo.plugin.v1.RuntimeHost.SetGlobalConfigEntry:output_type -> silo.plugin.v1.SetGlobalConfigEntryResponse
	23, // 38: silo.plugin.v1.RuntimeHost.ListLibraryMedia:output_type -> silo.plugin.v1.ListLibraryMediaResponse
	26, // 39: silo.plugin.v1.RuntimeHost.GetCatalogStats:output_type -> silo.plugin.v1.GetCatalogStatsResponse
	30, // 40: silo.plugin.v1.RuntimeHost.ResolveCatalogImageURLs:output_type -> silo.plugin.v1.ResolveCatalogImageURLsResponse
	32, // 41: silo.plugin.v1.RuntimeHost.MintScopedStream:output_type -> silo.plugin.v1.MintScopedStreamResponse
	34, // 42: silo.plugin.v1.RuntimeHost.CallPluginHTTP:output_type -> silo.plugin.v1.CallPluginHTTPResponse
	2,  // 43: silo.plugin.v1.RuntimeHost.UpsertVirtualMedia:output_type -> silo.plugin.v1.UpsertVirtualMediaResponse
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_runtime_host_proto_init() }
func file_silo_plugin_v1_runtime_host_proto_init() {
	if File_silo_plugin_v1_runtime_host_proto != nil {
		return
	}
	file_silo_plugin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_runtime_host_proto_rawDesc), len(file_silo_plugin_v1_runtime_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_runtime_host_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_runtime_host_proto_depIdxs,
		MessageInfos:      file_silo_plugin_v1_runtime_host_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_runtime_host_proto = out.File
	file_silo_plugin_v1_runtime_host_proto_goTypes = nil
	file_silo_plugin_v1_runtime_host_proto_depIdxs = nil
}
