// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/virtual_stream.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtualStreamProvider_ResolveVirtualStream_FullMethodName = "/silo.plugin.v1.VirtualStreamProvider/ResolveVirtualStream"
)

// VirtualStreamProviderClient is the client API for VirtualStreamProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VirtualStreamProvider defines the capability for resolving provider-neutral,
// just-in-time virtual stream results.
type VirtualStreamProviderClient interface {
	// ResolveVirtualStream resolves candidate streams for a given media request.
	ResolveVirtualStream(ctx context.Context, in *ResolveVirtualStreamRequest, opts ...grpc.CallOption) (*ResolveVirtualStreamResponse, error)
}

type virtualStreamProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualStreamProviderClient(cc grpc.ClientConnInterface) VirtualStreamProviderClient {
	return &virtualStreamProviderClient{cc}
}

func (c *virtualStreamProviderClient) ResolveVirtualStream(ctx context.Context, in *ResolveVirtualStreamRequest, opts ...grpc.CallOption) (*ResolveVirtualStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveVirtualStreamResponse)
	err := c.cc.Invoke(ctx, VirtualStreamProvider_ResolveVirtualStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualStreamProviderServer is the server API for VirtualStreamProvider service.
// All implementations should embed UnimplementedVirtualStreamProviderServer
// for forward compatibility.
//
// VirtualStreamProvider defines the capability for resolving provider-neutral,
// just-in-time virtual stream results.
type VirtualStreamProviderServer interface {
	// ResolveVirtualStream resolves candidate streams for a given media request.
	ResolveVirtualStream(context.Context, *ResolveVirtualStreamRequest) (*ResolveVirtualStreamResponse, error)
}

// UnimplementedVirtualStreamProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualStreamProviderServer struct{}

func (UnimplementedVirtualStreamProviderServer) ResolveVirtualStream(context.Context, *ResolveVirtualStreamRequest) (*ResolveVirtualStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveVirtualStream not implemented")
}
func (UnimplementedVirtualStreamProviderServer) testEmbeddedByValue() {}

// UnsafeVirtualStreamProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualStreamProviderServer will
// result in compilation errors.
type UnsafeVirtualStreamProviderServer interface {
	mustEmbedUnimplementedVirtualStreamProviderServer()
}

func RegisterVirtualStreamProviderServer(s grpc.ServiceRegistrar, srv VirtualStreamProviderServer) {
	// If the following call panics, it indicates UnimplementedVirtualStreamProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualStreamProvider_ServiceDesc, srv)
}

func _VirtualStreamProvider_ResolveVirtualStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveVirtualStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualStreamProviderServer).ResolveVirtualStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualStreamProvider_ResolveVirtualStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualStreamProviderServer).ResolveVirtualStream(ctx, req.(*ResolveVirtualStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualStreamProvider_ServiceDesc is the grpc.ServiceDesc for VirtualStreamProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualStreamProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.VirtualStreamProvider",
	HandlerType: (*VirtualStreamProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveVirtualStream",
			Handler:    _VirtualStreamProvider_ResolveVirtualStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/virtual_stream.proto",
}
