// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: silo/plugin/v1/virtual_stream.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VirtualStreamAvailabilityState indicates the readiness state of a virtual stream.
type VirtualStreamAvailabilityState int32

const (
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_UNSPECIFIED VirtualStreamAvailabilityState = 0
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_AVAILABLE   VirtualStreamAvailabilityState = 1
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_PENDING     VirtualStreamAvailabilityState = 2
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_UNRESOLVED  VirtualStreamAvailabilityState = 3
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_DEGRADED    VirtualStreamAvailabilityState = 4
	VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_UNAVAILABLE VirtualStreamAvailabilityState = 5
)

// Enum value maps for VirtualStreamAvailabilityState.
var (
	VirtualStreamAvailabilityState_name = map[int32]string{
		0: "VIRTUAL_STREAM_AVAILABILITY_STATE_UNSPECIFIED",
		1: "VIRTUAL_STREAM_AVAILABILITY_STATE_AVAILABLE",
		2: "VIRTUAL_STREAM_AVAILABILITY_STATE_PENDING",
		3: "VIRTUAL_STREAM_AVAILABILITY_STATE_UNRESOLVED",
		4: "VIRTUAL_STREAM_AVAILABILITY_STATE_DEGRADED",
		5: "VIRTUAL_STREAM_AVAILABILITY_STATE_UNAVAILABLE",
	}
	VirtualStreamAvailabilityState_value = map[string]int32{
		"VIRTUAL_STREAM_AVAILABILITY_STATE_UNSPECIFIED": 0,
		"VIRTUAL_STREAM_AVAILABILITY_STATE_AVAILABLE":   1,
		"VIRTUAL_STREAM_AVAILABILITY_STATE_PENDING":     2,
		"VIRTUAL_STREAM_AVAILABILITY_STATE_UNRESOLVED":  3,
		"VIRTUAL_STREAM_AVAILABILITY_STATE_DEGRADED":    4,
		"VIRTUAL_STREAM_AVAILABILITY_STATE_UNAVAILABLE": 5,
	}
)

func (x VirtualStreamAvailabilityState) Enum() *VirtualStreamAvailabilityState {
	p := new(VirtualStreamAvailabilityState)
	*p = x
	return p
}

func (x VirtualStreamAvailabilityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualStreamAvailabilityState) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_virtual_stream_proto_enumTypes[0].Descriptor()
}

func (VirtualStreamAvailabilityState) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_virtual_stream_proto_enumTypes[0]
}

func (x VirtualStreamAvailabilityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualStreamAvailabilityState.Descriptor instead.
func (VirtualStreamAvailabilityState) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{0}
}

// VirtualStreamErrorCode identifies standard virtual stream fault categories.
type VirtualStreamErrorCode int32

const (
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_UNSPECIFIED      VirtualStreamErrorCode = 0
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_NOT_FOUND        VirtualStreamErrorCode = 1
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_TEMPORARY        VirtualStreamErrorCode = 2
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_EXPIRED          VirtualStreamErrorCode = 3
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_RATE_LIMITED     VirtualStreamErrorCode = 4
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_UNAUTHORIZED     VirtualStreamErrorCode = 5
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_PROVIDER_FAILURE VirtualStreamErrorCode = 6
	VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_PERMANENT        VirtualStreamErrorCode = 7
)

// Enum value maps for VirtualStreamErrorCode.
var (
	VirtualStreamErrorCode_name = map[int32]string{
		0: "VIRTUAL_STREAM_ERROR_CODE_UNSPECIFIED",
		1: "VIRTUAL_STREAM_ERROR_CODE_NOT_FOUND",
		2: "VIRTUAL_STREAM_ERROR_CODE_TEMPORARY",
		3: "VIRTUAL_STREAM_ERROR_CODE_EXPIRED",
		4: "VIRTUAL_STREAM_ERROR_CODE_RATE_LIMITED",
		5: "VIRTUAL_STREAM_ERROR_CODE_UNAUTHORIZED",
		6: "VIRTUAL_STREAM_ERROR_CODE_PROVIDER_FAILURE",
		7: "VIRTUAL_STREAM_ERROR_CODE_PERMANENT",
	}
	VirtualStreamErrorCode_value = map[string]int32{
		"VIRTUAL_STREAM_ERROR_CODE_UNSPECIFIED":      0,
		"VIRTUAL_STREAM_ERROR_CODE_NOT_FOUND":        1,
		"VIRTUAL_STREAM_ERROR_CODE_TEMPORARY":        2,
		"VIRTUAL_STREAM_ERROR_CODE_EXPIRED":          3,
		"VIRTUAL_STREAM_ERROR_CODE_RATE_LIMITED":     4,
		"VIRTUAL_STREAM_ERROR_CODE_UNAUTHORIZED":     5,
		"VIRTUAL_STREAM_ERROR_CODE_PROVIDER_FAILURE": 6,
		"VIRTUAL_STREAM_ERROR_CODE_PERMANENT":        7,
	}
)

func (x VirtualStreamErrorCode) Enum() *VirtualStreamErrorCode {
	p := new(VirtualStreamErrorCode)
	*p = x
	return p
}

func (x VirtualStreamErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualStreamErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_silo_plugin_v1_virtual_stream_proto_enumTypes[1].Descriptor()
}

func (VirtualStreamErrorCode) Type() protoreflect.EnumType {
	return &file_silo_plugin_v1_virtual_stream_proto_enumTypes[1]
}

func (x VirtualStreamErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualStreamErrorCode.Descriptor instead.
func (VirtualStreamErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{1}
}

type VirtualStreamProfile struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Label      string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Resolution string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	VideoCodec string                 `protobuf:"bytes,3,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec string                 `protobuf:"bytes,4,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	HdrFormat  string                 `protobuf:"bytes,5,opt,name=hdr_format,json=hdrFormat,proto3" json:"hdr_format,omitempty"`
	// When true, selecting this profile asks for the provider's complete ranked
	// result set instead of applying a quality constraint.
	AllResults    bool `protobuf:"varint,6,opt,name=all_results,json=allResults,proto3" json:"all_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualStreamProfile) Reset() {
	*x = VirtualStreamProfile{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamProfile) ProtoMessage() {}

func (x *VirtualStreamProfile) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamProfile.ProtoReflect.Descriptor instead.
func (*VirtualStreamProfile) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualStreamProfile) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *VirtualStreamProfile) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *VirtualStreamProfile) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *VirtualStreamProfile) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *VirtualStreamProfile) GetHdrFormat() string {
	if x != nil {
		return x.HdrFormat
	}
	return ""
}

func (x *VirtualStreamProfile) GetAllResults() bool {
	if x != nil {
		return x.AllResults
	}
	return false
}

type ListVirtualStreamProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVirtualStreamProfilesRequest) Reset() {
	*x = ListVirtualStreamProfilesRequest{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVirtualStreamProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVirtualStreamProfilesRequest) ProtoMessage() {}

func (x *ListVirtualStreamProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVirtualStreamProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListVirtualStreamProfilesRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ListVirtualStreamProfilesRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ListVirtualStreamProfilesRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type ListVirtualStreamProfilesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Profiles      []*VirtualStreamProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVirtualStreamProfilesResponse) Reset() {
	*x = ListVirtualStreamProfilesResponse{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVirtualStreamProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVirtualStreamProfilesResponse) ProtoMessage() {}

func (x *ListVirtualStreamProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVirtualStreamProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListVirtualStreamProfilesResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{2}
}

func (x *ListVirtualStreamProfilesResponse) GetProfiles() []*VirtualStreamProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// VirtualStreamProviderDescriptor advertises a plugin's virtual stream provider
// features and media format support in its manifest.
type VirtualStreamProviderDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media types supported by this virtual stream provider (e.g. "movie", "episode").
	SupportedMediaTypes []string `protobuf:"bytes,1,rep,name=supported_media_types,json=supportedMediaTypes,proto3" json:"supported_media_types,omitempty"`
	// Container formats supported (e.g. "mkv", "mp4", "ts", "hls").
	SupportedContainers []string `protobuf:"bytes,2,rep,name=supported_containers,json=supportedContainers,proto3" json:"supported_containers,omitempty"`
	// Indicates whether the provider supports dynamic just-in-time resolution.
	SupportsJustInTimeResolution bool `protobuf:"varint,3,opt,name=supports_just_in_time_resolution,json=supportsJustInTimeResolution,proto3" json:"supports_just_in_time_resolution,omitempty"`
	// Indicates whether the provider can return multiple stream candidates.
	SupportsMultipleCandidates bool `protobuf:"varint,4,opt,name=supports_multiple_candidates,json=supportsMultipleCandidates,proto3" json:"supports_multiple_candidates,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VirtualStreamProviderDescriptor) Reset() {
	*x = VirtualStreamProviderDescriptor{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamProviderDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamProviderDescriptor) ProtoMessage() {}

func (x *VirtualStreamProviderDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamProviderDescriptor.ProtoReflect.Descriptor instead.
func (*VirtualStreamProviderDescriptor) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualStreamProviderDescriptor) GetSupportedMediaTypes() []string {
	if x != nil {
		return x.SupportedMediaTypes
	}
	return nil
}

func (x *VirtualStreamProviderDescriptor) GetSupportedContainers() []string {
	if x != nil {
		return x.SupportedContainers
	}
	return nil
}

func (x *VirtualStreamProviderDescriptor) GetSupportsJustInTimeResolution() bool {
	if x != nil {
		return x.SupportsJustInTimeResolution
	}
	return false
}

func (x *VirtualStreamProviderDescriptor) GetSupportsMultipleCandidates() bool {
	if x != nil {
		return x.SupportsMultipleCandidates
	}
	return false
}

// VirtualStreamResolution describes the display resolution and framerate of a stream.
type VirtualStreamResolution struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Width  int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Standard resolution label (e.g. "1080p", "2160p", "4k", "720p").
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Frame rate in frames per second (e.g. 23.976, 60.0).
	FrameRate     float64 `protobuf:"fixed64,4,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualStreamResolution) Reset() {
	*x = VirtualStreamResolution{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamResolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamResolution) ProtoMessage() {}

func (x *VirtualStreamResolution) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamResolution.ProtoReflect.Descriptor instead.
func (*VirtualStreamResolution) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{4}
}

func (x *VirtualStreamResolution) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VirtualStreamResolution) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VirtualStreamResolution) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *VirtualStreamResolution) GetFrameRate() float64 {
	if x != nil {
		return x.FrameRate
	}
	return 0
}

// VirtualStreamHDR describes High Dynamic Range and Dolby Vision characteristics.
type VirtualStreamHDR struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	IsHdr bool                   `protobuf:"varint,1,opt,name=is_hdr,json=isHdr,proto3" json:"is_hdr,omitempty"`
	// Primary HDR format (e.g. "HDR10", "HDR10+", "HLG", "Dolby Vision").
	Format         string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	HasDolbyVision bool   `protobuf:"varint,3,opt,name=has_dolby_vision,json=hasDolbyVision,proto3" json:"has_dolby_vision,omitempty"`
	// Dolby Vision profile string (e.g. "Profile 5", "Profile 8.1").
	DolbyVisionProfile string `protobuf:"bytes,4,opt,name=dolby_vision_profile,json=dolbyVisionProfile,proto3" json:"dolby_vision_profile,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VirtualStreamHDR) Reset() {
	*x = VirtualStreamHDR{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamHDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamHDR) ProtoMessage() {}

func (x *VirtualStreamHDR) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamHDR.ProtoReflect.Descriptor instead.
func (*VirtualStreamHDR) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{5}
}

func (x *VirtualStreamHDR) GetIsHdr() bool {
	if x != nil {
		return x.IsHdr
	}
	return false
}

func (x *VirtualStreamHDR) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *VirtualStreamHDR) GetHasDolbyVision() bool {
	if x != nil {
		return x.HasDolbyVision
	}
	return false
}

func (x *VirtualStreamHDR) GetDolbyVisionProfile() string {
	if x != nil {
		return x.DolbyVisionProfile
	}
	return ""
}

// VirtualStreamAvailability describes stream readiness and progress metadata.
type VirtualStreamAvailability struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	State VirtualStreamAvailabilityState `protobuf:"varint,1,opt,name=state,proto3,enum=silo.plugin.v1.VirtualStreamAvailabilityState" json:"state,omitempty"`
	// Operator or client safe description of the availability state.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp when the stream is expected to become available (for pending streams).
	EstimatedReadyAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=estimated_ready_at,json=estimatedReadyAt,proto3" json:"estimated_ready_at,omitempty"`
	// Progress percentage (0 to 100) for buffering, downloading, or processing streams.
	ProgressPercent int32 `protobuf:"varint,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VirtualStreamAvailability) Reset() {
	*x = VirtualStreamAvailability{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamAvailability) ProtoMessage() {}

func (x *VirtualStreamAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamAvailability.ProtoReflect.Descriptor instead.
func (*VirtualStreamAvailability) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{6}
}

func (x *VirtualStreamAvailability) GetState() VirtualStreamAvailabilityState {
	if x != nil {
		return x.State
	}
	return VirtualStreamAvailabilityState_VIRTUAL_STREAM_AVAILABILITY_STATE_UNSPECIFIED
}

func (x *VirtualStreamAvailability) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VirtualStreamAvailability) GetEstimatedReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedReadyAt
	}
	return nil
}

func (x *VirtualStreamAvailability) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

// VirtualStreamError provides structured fault metadata for stream failures.
type VirtualStreamError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  VirtualStreamErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=silo.plugin.v1.VirtualStreamErrorCode" json:"code,omitempty"`
	// Safe error message suitable for client display or logging.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Indicates whether the operation can be retried.
	Retryable bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Recommended delay before attempting a retry.
	RetryAfter    *durationpb.Duration `protobuf:"bytes,4,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualStreamError) Reset() {
	*x = VirtualStreamError{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamError) ProtoMessage() {}

func (x *VirtualStreamError) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamError.ProtoReflect.Descriptor instead.
func (*VirtualStreamError) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{7}
}

func (x *VirtualStreamError) GetCode() VirtualStreamErrorCode {
	if x != nil {
		return x.Code
	}
	return VirtualStreamErrorCode_VIRTUAL_STREAM_ERROR_CODE_UNSPECIFIED
}

func (x *VirtualStreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VirtualStreamError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *VirtualStreamError) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

// VirtualStreamCandidate represents one candidate stream available for just-in-time playback.
type VirtualStreamCandidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique candidate identifier.
	CandidateId string `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Identifier of the stream provider or source plugin.
	ProviderId string `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Temporary URI for just-in-time stream playback.
	TemporaryUri string `protobuf:"bytes,3,opt,name=temporary_uri,json=temporaryUri,proto3" json:"temporary_uri,omitempty"`
	// Expiration timestamp of the temporary URI or stream access.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Preference ranking (e.g. 1 = primary / highest preference).
	Rank int32 `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	// Video resolution metadata.
	Resolution *VirtualStreamResolution `protobuf:"bytes,6,opt,name=resolution,proto3" json:"resolution,omitempty"`
	// Video codec identifier (e.g. "hevc", "h264", "av1", "vp9").
	VideoCodec string `protobuf:"bytes,7,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	// Primary audio codec identifier (e.g. "aac", "ac3", "eac3", "truehd", "dts", "flac").
	AudioCodec string `protobuf:"bytes,8,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	// HDR and Dolby Vision metadata.
	Hdr *VirtualStreamHDR `protobuf:"bytes,9,opt,name=hdr,proto3" json:"hdr,omitempty"`
	// Bitrate in bits per second (bps).
	Bitrate int64 `protobuf:"varint,10,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Media file size in bytes.
	FileSizeBytes int64 `protobuf:"varint,11,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	// Container format (e.g. "mkv", "mp4", "ts", "hls").
	Container string `protobuf:"bytes,12,opt,name=container,proto3" json:"container,omitempty"`
	// Available audio track languages (BCP 47 or ISO 639 codes).
	AudioLanguages []string `protobuf:"bytes,13,rep,name=audio_languages,json=audioLanguages,proto3" json:"audio_languages,omitempty"`
	// Available subtitle track languages (BCP 47 or ISO 639 codes).
	SubtitleLanguages []string `protobuf:"bytes,14,rep,name=subtitle_languages,json=subtitleLanguages,proto3" json:"subtitle_languages,omitempty"`
	// Candidate-specific availability metadata.
	Availability *VirtualStreamAvailability `protobuf:"bytes,15,opt,name=availability,proto3" json:"availability,omitempty"`
	// Candidate-specific error metadata (when degraded or failed).
	Error *VirtualStreamError `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	// Arbitrary provider-specific metadata.
	Metadata      *structpb.Struct `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualStreamCandidate) Reset() {
	*x = VirtualStreamCandidate{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamCandidate) ProtoMessage() {}

func (x *VirtualStreamCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamCandidate.ProtoReflect.Descriptor instead.
func (*VirtualStreamCandidate) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{8}
}

func (x *VirtualStreamCandidate) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VirtualStreamCandidate) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *VirtualStreamCandidate) GetTemporaryUri() string {
	if x != nil {
		return x.TemporaryUri
	}
	return ""
}

func (x *VirtualStreamCandidate) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VirtualStreamCandidate) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *VirtualStreamCandidate) GetResolution() *VirtualStreamResolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *VirtualStreamCandidate) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *VirtualStreamCandidate) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *VirtualStreamCandidate) GetHdr() *VirtualStreamHDR {
	if x != nil {
		return x.Hdr
	}
	return nil
}

func (x *VirtualStreamCandidate) GetBitrate() int64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *VirtualStreamCandidate) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *VirtualStreamCandidate) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *VirtualStreamCandidate) GetAudioLanguages() []string {
	if x != nil {
		return x.AudioLanguages
	}
	return nil
}

func (x *VirtualStreamCandidate) GetSubtitleLanguages() []string {
	if x != nil {
		return x.SubtitleLanguages
	}
	return nil
}

func (x *VirtualStreamCandidate) GetAvailability() *VirtualStreamAvailability {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *VirtualStreamCandidate) GetError() *VirtualStreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *VirtualStreamCandidate) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// VirtualStreamResult contains the provider-neutral resolution outcome for just-in-time playback,
// supporting multiple candidate streams, availability, and error metadata.
type VirtualStreamResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique resolution result identifier.
	ResultId string `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	// Primary provider identifier.
	ProviderId string `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Multiple candidate streams ordered by rank/preference.
	Candidates []*VirtualStreamCandidate `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// Overall stream resolution availability metadata.
	Availability *VirtualStreamAvailability `protobuf:"bytes,4,opt,name=availability,proto3" json:"availability,omitempty"`
	// Overall stream resolution error metadata.
	Error *VirtualStreamError `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Arbitrary provider or resolution metadata.
	Metadata      *structpb.Struct `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualStreamResult) Reset() {
	*x = VirtualStreamResult{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualStreamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualStreamResult) ProtoMessage() {}

func (x *VirtualStreamResult) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualStreamResult.ProtoReflect.Descriptor instead.
func (*VirtualStreamResult) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{9}
}

func (x *VirtualStreamResult) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *VirtualStreamResult) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *VirtualStreamResult) GetCandidates() []*VirtualStreamCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *VirtualStreamResult) GetAvailability() *VirtualStreamAvailability {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *VirtualStreamResult) GetError() *VirtualStreamError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *VirtualStreamResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ResolveVirtualStreamRequest is sent to resolve stream candidates for a media item.
type ResolveVirtualStreamRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	// Media type (e.g. "movie", "episode", "track").
	MediaType     string            `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Title         string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32             `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	ExternalIds   map[string]string `protobuf:"bytes,5,rep,name=external_ids,json=externalIds,proto3" json:"external_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeasonNumber  int32             `protobuf:"varint,6,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeNumber int32             `protobuf:"varint,7,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Metadata      *structpb.Struct  `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveVirtualStreamRequest) Reset() {
	*x = ResolveVirtualStreamRequest{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVirtualStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVirtualStreamRequest) ProtoMessage() {}

func (x *ResolveVirtualStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVirtualStreamRequest.ProtoReflect.Descriptor instead.
func (*ResolveVirtualStreamRequest) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveVirtualStreamRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ResolveVirtualStreamRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ResolveVirtualStreamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResolveVirtualStreamRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ResolveVirtualStreamRequest) GetExternalIds() map[string]string {
	if x != nil {
		return x.ExternalIds
	}
	return nil
}

func (x *ResolveVirtualStreamRequest) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *ResolveVirtualStreamRequest) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *ResolveVirtualStreamRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ResolveVirtualStreamResponse wraps the virtual stream resolution result.
type ResolveVirtualStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *VirtualStreamResult   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveVirtualStreamResponse) Reset() {
	*x = ResolveVirtualStreamResponse{}
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVirtualStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVirtualStreamResponse) ProtoMessage() {}

func (x *ResolveVirtualStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_silo_plugin_v1_virtual_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVirtualStreamResponse.ProtoReflect.Descriptor instead.
func (*ResolveVirtualStreamResponse) Descriptor() ([]byte, []int) {
	return file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveVirtualStreamResponse) GetResult() *VirtualStreamResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_silo_plugin_v1_virtual_stream_proto protoreflect.FileDescriptor

const file_silo_plugin_v1_virtual_stream_proto_rawDesc = "" +
	"\n" +
	"#silo/plugin/v1/virtual_stream.proto\x12\x0esilo.plugin.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\x14VirtualStreamProfile\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x1f\n" +
	"\vvideo_codec\x18\x03 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x04 \x01(\tR\n" +
	"audioCodec\x12\x1d\n" +
	"\n" +
	"hdr_format\x18\x05 \x01(\tR\thdrFormat\x12\x1f\n" +
	"\vall_results\x18\x06 \x01(\bR\n" +
	"allResults\"f\n" +
	" ListVirtualStreamProfilesRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\"e\n" +
	"!ListVirtualStreamProfilesResponse\x12@\n" +
	"\bprofiles\x18\x01 \x03(\v2$.silo.plugin.v1.VirtualStreamProfileR\bprofiles\"\x92\x02\n" +
	"\x1fVirtualStreamProviderDescriptor\x122\n" +
	"\x15supported_media_types\x18\x01 \x03(\tR\x13supportedMediaTypes\x121\n" +
	"\x14supported_containers\x18\x02 \x03(\tR\x13supportedContainers\x12F\n" +
	" supports_just_in_time_resolution\x18\x03 \x01(\bR\x1csupportsJustInTimeResolution\x12@\n" +
	"\x1csupports_multiple_candidates\x18\x04 \x01(\bR\x1asupportsMultipleCandidates\"|\n" +
	"\x17VirtualStreamResolution\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"frame_rate\x18\x04 \x01(\x01R\tframeRate\"\x9d\x01\n" +
	"\x10VirtualStreamHDR\x12\x15\n" +
	"\x06is_hdr\x18\x01 \x01(\bR\x05isHdr\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12(\n" +
	"\x10has_dolby_vision\x18\x03 \x01(\bR\x0ehasDolbyVision\x120\n" +
	"\x14dolby_vision_profile\x18\x04 \x01(\tR\x12dolbyVisionProfile\"\xf0\x01\n" +
	"\x19VirtualStreamAvailability\x12D\n" +
	"\x05state\x18\x01 \x01(\x0e2..silo.plugin.v1.VirtualStreamAvailabilityStateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\x12estimated_ready_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10estimatedReadyAt\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x05R\x0fprogressPercent\"\xc4\x01\n" +
	"\x12VirtualStreamError\x12:\n" +
	"\x04code\x18\x01 \x01(\x0e2&.silo.plugin.v1.VirtualStreamErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12:\n" +
	"\vretry_after\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\"\x85\x06\n" +
	"\x16VirtualStreamCandidate\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rtemporary_uri\x18\x03 \x01(\tR\ftemporaryUri\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12G\n" +
	"\n" +
	"resolution\x18\x06 \x01(\v2'.silo.plugin.v1.VirtualStreamResolutionR\n" +
	"resolution\x12\x1f\n" +
	"\vvideo_codec\x18\a \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\b \x01(\tR\n" +
	"audioCodec\x122\n" +
	"\x03hdr\x18\t \x01(\v2 .silo.plugin.v1.VirtualStreamHDRR\x03hdr\x12\x18\n" +
	"\abitrate\x18\n" +
	" \x01(\x03R\abitrate\x12&\n" +
	"\x0ffile_size_bytes\x18\v \x01(\x03R\rfileSizeBytes\x12\x1c\n" +
	"\tcontainer\x18\f \x01(\tR\tcontainer\x12'\n" +
	"\x0faudio_languages\x18\r \x03(\tR\x0eaudioLanguages\x12-\n" +
	"\x12subtitle_languages\x18\x0e \x03(\tR\x11subtitleLanguages\x12M\n" +
	"\favailability\x18\x0f \x01(\v2).silo.plugin.v1.VirtualStreamAvailabilityR\favailability\x128\n" +
	"\x05error\x18\x10 \x01(\v2\".silo.plugin.v1.VirtualStreamErrorR\x05error\x123\n" +
	"\bmetadata\x18\x11 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xd9\x02\n" +
	"\x13VirtualStreamResult\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12F\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2&.silo.plugin.v1.VirtualStreamCandidateR\n" +
	"candidates\x12M\n" +
	"\favailability\x18\x04 \x01(\v2).silo.plugin.v1.VirtualStreamAvailabilityR\favailability\x128\n" +
	"\x05error\x18\x05 \x01(\v2\".silo.plugin.v1.VirtualStreamErrorR\x05error\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xad\x03\n" +
	"\x1bResolveVirtualStreamRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12_\n" +
	"\fexternal_ids\x18\x05 \x03(\v2<.silo.plugin.v1.ResolveVirtualStreamRequest.ExternalIdsEntryR\vexternalIds\x12#\n" +
	"\rseason_number\x18\x06 \x01(\x05R\fseasonNumber\x12%\n" +
	"\x0eepisode_number\x18\a \x01(\x05R\repisodeNumber\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x1a>\n" +
	"\x10ExternalIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x1cResolveVirtualStreamResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.silo.plugin.v1.VirtualStreamResultR\x06result*\xc8\x02\n" +
	"\x1eVirtualStreamAvailabilityState\x121\n" +
	"-VIRTUAL_STREAM_AVAILABILITY_STATE_UNSPECIFIED\x10\x00\x12/\n" +
	"+VIRTUAL_STREAM_AVAILABILITY_STATE_AVAILABLE\x10\x01\x12-\n" +
	")VIRTUAL_STREAM_AVAILABILITY_STATE_PENDING\x10\x02\x120\n" +
	",VIRTUAL_STREAM_AVAILABILITY_STATE_UNRESOLVED\x10\x03\x12.\n" +
	"*VIRTUAL_STREAM_AVAILABILITY_STATE_DEGRADED\x10\x04\x121\n" +
	"-VIRTUAL_STREAM_AVAILABILITY_STATE_UNAVAILABLE\x10\x05*\xed\x02\n" +
	"\x16VirtualStreamErrorCode\x12)\n" +
	"%VIRTUAL_STREAM_ERROR_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#VIRTUAL_STREAM_ERROR_CODE_NOT_FOUND\x10\x01\x12'\n" +
	"#VIRTUAL_STREAM_ERROR_CODE_TEMPORARY\x10\x02\x12%\n" +
	"!VIRTUAL_STREAM_ERROR_CODE_EXPIRED\x10\x03\x12*\n" +
	"&VIRTUAL_STREAM_ERROR_CODE_RATE_LIMITED\x10\x04\x12*\n" +
	"&VIRTUAL_STREAM_ERROR_CODE_UNAUTHORIZED\x10\x05\x12.\n" +
	"*VIRTUAL_STREAM_ERROR_CODE_PROVIDER_FAILURE\x10\x06\x12'\n" +
	"#VIRTUAL_STREAM_ERROR_CODE_PERMANENT\x10\a2\x8d\x02\n" +
	"\x15VirtualStreamProvider\x12q\n" +
	"\x14ResolveVirtualStream\x12+.silo.plugin.v1.ResolveVirtualStreamRequest\x1a,.silo.plugin.v1.ResolveVirtualStreamResponse\x12\x80\x01\n" +
	"\x19ListVirtualStreamProfiles\x120.silo.plugin.v1.ListVirtualStreamProfilesRequest\x1a1.silo.plugin.v1.ListVirtualStreamProfilesResponseBPZNgithub.com/Silo-Server/silo-plugin-sdk/pkg/pluginproto/silo/plugin/v1;pluginv1b\x06proto3"

var (
	file_silo_plugin_v1_virtual_stream_proto_rawDescOnce sync.Once
	file_silo_plugin_v1_virtual_stream_proto_rawDescData []byte
)

func file_silo_plugin_v1_virtual_stream_proto_rawDescGZIP() []byte {
	file_silo_plugin_v1_virtual_stream_proto_rawDescOnce.Do(func() {
		file_silo_plugin_v1_virtual_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_virtual_stream_proto_rawDesc), len(file_silo_plugin_v1_virtual_stream_proto_rawDesc)))
	})
	return file_silo_plugin_v1_virtual_stream_proto_rawDescData
}

var file_silo_plugin_v1_virtual_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_silo_plugin_v1_virtual_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_silo_plugin_v1_virtual_stream_proto_goTypes = []any{
	(VirtualStreamAvailabilityState)(0),       // 0: silo.plugin.v1.VirtualStreamAvailabilityState
	(VirtualStreamErrorCode)(0),               // 1: silo.plugin.v1.VirtualStreamErrorCode
	(*VirtualStreamProfile)(nil),              // 2: silo.plugin.v1.VirtualStreamProfile
	(*ListVirtualStreamProfilesRequest)(nil),  // 3: silo.plugin.v1.ListVirtualStreamProfilesRequest
	(*ListVirtualStreamProfilesResponse)(nil), // 4: silo.plugin.v1.ListVirtualStreamProfilesResponse
	(*VirtualStreamProviderDescriptor)(nil),   // 5: silo.plugin.v1.VirtualStreamProviderDescriptor
	(*VirtualStreamResolution)(nil),           // 6: silo.plugin.v1.VirtualStreamResolution
	(*VirtualStreamHDR)(nil),                  // 7: silo.plugin.v1.VirtualStreamHDR
	(*VirtualStreamAvailability)(nil),         // 8: silo.plugin.v1.VirtualStreamAvailability
	(*VirtualStreamError)(nil),                // 9: silo.plugin.v1.VirtualStreamError
	(*VirtualStreamCandidate)(nil),            // 10: silo.plugin.v1.VirtualStreamCandidate
	(*VirtualStreamResult)(nil),               // 11: silo.plugin.v1.VirtualStreamResult
	(*ResolveVirtualStreamRequest)(nil),       // 12: silo.plugin.v1.ResolveVirtualStreamRequest
	(*ResolveVirtualStreamResponse)(nil),      // 13: silo.plugin.v1.ResolveVirtualStreamResponse
	nil,                                       // 14: silo.plugin.v1.ResolveVirtualStreamRequest.ExternalIdsEntry
	(*timestamppb.Timestamp)(nil),             // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),               // 16: google.protobuf.Duration
	(*structpb.Struct)(nil),                   // 17: google.protobuf.Struct
}
var file_silo_plugin_v1_virtual_stream_proto_depIdxs = []int32{
	2,  // 0: silo.plugin.v1.ListVirtualStreamProfilesResponse.profiles:type_name -> silo.plugin.v1.VirtualStreamProfile
	0,  // 1: silo.plugin.v1.VirtualStreamAvailability.state:type_name -> silo.plugin.v1.VirtualStreamAvailabilityState
	15, // 2: silo.plugin.v1.VirtualStreamAvailability.estimated_ready_at:type_name -> google.protobuf.Timestamp
	1,  // 3: silo.plugin.v1.VirtualStreamError.code:type_name -> silo.plugin.v1.VirtualStreamErrorCode
	16, // 4: silo.plugin.v1.VirtualStreamError.retry_after:type_name -> google.protobuf.Duration
	15, // 5: silo.plugin.v1.VirtualStreamCandidate.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 6: silo.plugin.v1.VirtualStreamCandidate.resolution:type_name -> silo.plugin.v1.VirtualStreamResolution
	7,  // 7: silo.plugin.v1.VirtualStreamCandidate.hdr:type_name -> silo.plugin.v1.VirtualStreamHDR
	8,  // 8: silo.plugin.v1.VirtualStreamCandidate.availability:type_name -> silo.plugin.v1.VirtualStreamAvailability
	9,  // 9: silo.plugin.v1.VirtualStreamCandidate.error:type_name -> silo.plugin.v1.VirtualStreamError
	17, // 10: silo.plugin.v1.VirtualStreamCandidate.metadata:type_name -> google.protobuf.Struct
	10, // 11: silo.plugin.v1.VirtualStreamResult.candidates:type_name -> silo.plugin.v1.VirtualStreamCandidate
	8,  // 12: silo.plugin.v1.VirtualStreamResult.availability:type_name -> silo.plugin.v1.VirtualStreamAvailability
	9,  // 13: silo.plugin.v1.VirtualStreamResult.error:type_name -> silo.plugin.v1.VirtualStreamError
	17, // 14: silo.plugin.v1.VirtualStreamResult.metadata:type_name -> google.protobuf.Struct
	14, // 15: silo.plugin.v1.ResolveVirtualStreamRequest.external_ids:type_name -> silo.plugin.v1.ResolveVirtualStreamRequest.ExternalIdsEntry
	17, // 16: silo.plugin.v1.ResolveVirtualStreamRequest.metadata:type_name -> google.protobuf.Struct
	11, // 17: silo.plugin.v1.ResolveVirtualStreamResponse.result:type_name -> silo.plugin.v1.VirtualStreamResult
	12, // 18: silo.plugin.v1.VirtualStreamProvider.ResolveVirtualStream:input_type -> silo.plugin.v1.ResolveVirtualStreamRequest
	3,  // 19: silo.plugin.v1.VirtualStreamProvider.ListVirtualStreamProfiles:input_type -> silo.plugin.v1.ListVirtualStreamProfilesRequest
	13, // 20: silo.plugin.v1.VirtualStreamProvider.ResolveVirtualStream:output_type -> silo.plugin.v1.ResolveVirtualStreamResponse
	4,  // 21: silo.plugin.v1.VirtualStreamProvider.ListVirtualStreamProfiles:output_type -> silo.plugin.v1.ListVirtualStreamProfilesResponse
	20, // [20:22] is the sub-list for method output_type
	18, // [18:20] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_silo_plugin_v1_virtual_stream_proto_init() }
func file_silo_plugin_v1_virtual_stream_proto_init() {
	if File_silo_plugin_v1_virtual_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_silo_plugin_v1_virtual_stream_proto_rawDesc), len(file_silo_plugin_v1_virtual_stream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_silo_plugin_v1_virtual_stream_proto_goTypes,
		DependencyIndexes: file_silo_plugin_v1_virtual_stream_proto_depIdxs,
		EnumInfos:         file_silo_plugin_v1_virtual_stream_proto_enumTypes,
		MessageInfos:      file_silo_plugin_v1_virtual_stream_proto_msgTypes,
	}.Build()
	File_silo_plugin_v1_virtual_stream_proto = out.File
	file_silo_plugin_v1_virtual_stream_proto_goTypes = nil
	file_silo_plugin_v1_virtual_stream_proto_depIdxs = nil
}
