// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: silo/plugin/v1/watch_sync_provider.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WatchSyncProvider_InitAuthorize_FullMethodName      = "/silo.plugin.v1.WatchSyncProvider/InitAuthorize"
	WatchSyncProvider_ExchangeCode_FullMethodName       = "/silo.plugin.v1.WatchSyncProvider/ExchangeCode"
	WatchSyncProvider_ExchangeAPIKey_FullMethodName     = "/silo.plugin.v1.WatchSyncProvider/ExchangeAPIKey"
	WatchSyncProvider_RefreshCredentials_FullMethodName = "/silo.plugin.v1.WatchSyncProvider/RefreshCredentials"
	WatchSyncProvider_GetAccount_FullMethodName         = "/silo.plugin.v1.WatchSyncProvider/GetAccount"
	WatchSyncProvider_ApplyEvents_FullMethodName        = "/silo.plugin.v1.WatchSyncProvider/ApplyEvents"
	WatchSyncProvider_ListRemoteState_FullMethodName    = "/silo.plugin.v1.WatchSyncProvider/ListRemoteState"
)

// WatchSyncProviderClient is the client API for WatchSyncProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WatchSyncProvider adapts an external watch-tracking service to Silo's
// host-owned credential, outbox, retry, and reconciliation pipeline. Plugins
// must treat credentials and provider secrets as transient request data and
// must not persist or log them.
type WatchSyncProviderClient interface {
	InitAuthorize(ctx context.Context, in *WatchSyncInitAuthorizeRequest, opts ...grpc.CallOption) (*WatchSyncInitAuthorizeResponse, error)
	ExchangeCode(ctx context.Context, in *WatchSyncExchangeCodeRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error)
	ExchangeAPIKey(ctx context.Context, in *WatchSyncExchangeAPIKeyRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error)
	RefreshCredentials(ctx context.Context, in *WatchSyncRefreshCredentialsRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error)
	GetAccount(ctx context.Context, in *WatchSyncGetAccountRequest, opts ...grpc.CallOption) (*WatchSyncGetAccountResponse, error)
	ApplyEvents(ctx context.Context, in *WatchSyncApplyEventsRequest, opts ...grpc.CallOption) (*WatchSyncApplyEventsResponse, error)
	ListRemoteState(ctx context.Context, in *WatchSyncListRemoteStateRequest, opts ...grpc.CallOption) (*WatchSyncListRemoteStateResponse, error)
}

type watchSyncProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchSyncProviderClient(cc grpc.ClientConnInterface) WatchSyncProviderClient {
	return &watchSyncProviderClient{cc}
}

func (c *watchSyncProviderClient) InitAuthorize(ctx context.Context, in *WatchSyncInitAuthorizeRequest, opts ...grpc.CallOption) (*WatchSyncInitAuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncInitAuthorizeResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_InitAuthorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) ExchangeCode(ctx context.Context, in *WatchSyncExchangeCodeRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncCredentialResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_ExchangeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) ExchangeAPIKey(ctx context.Context, in *WatchSyncExchangeAPIKeyRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncCredentialResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_ExchangeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) RefreshCredentials(ctx context.Context, in *WatchSyncRefreshCredentialsRequest, opts ...grpc.CallOption) (*WatchSyncCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncCredentialResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_RefreshCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) GetAccount(ctx context.Context, in *WatchSyncGetAccountRequest, opts ...grpc.CallOption) (*WatchSyncGetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncGetAccountResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) ApplyEvents(ctx context.Context, in *WatchSyncApplyEventsRequest, opts ...grpc.CallOption) (*WatchSyncApplyEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncApplyEventsResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_ApplyEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchSyncProviderClient) ListRemoteState(ctx context.Context, in *WatchSyncListRemoteStateRequest, opts ...grpc.CallOption) (*WatchSyncListRemoteStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchSyncListRemoteStateResponse)
	err := c.cc.Invoke(ctx, WatchSyncProvider_ListRemoteState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchSyncProviderServer is the server API for WatchSyncProvider service.
// All implementations should embed UnimplementedWatchSyncProviderServer
// for forward compatibility.
//
// WatchSyncProvider adapts an external watch-tracking service to Silo's
// host-owned credential, outbox, retry, and reconciliation pipeline. Plugins
// must treat credentials and provider secrets as transient request data and
// must not persist or log them.
type WatchSyncProviderServer interface {
	InitAuthorize(context.Context, *WatchSyncInitAuthorizeRequest) (*WatchSyncInitAuthorizeResponse, error)
	ExchangeCode(context.Context, *WatchSyncExchangeCodeRequest) (*WatchSyncCredentialResponse, error)
	ExchangeAPIKey(context.Context, *WatchSyncExchangeAPIKeyRequest) (*WatchSyncCredentialResponse, error)
	RefreshCredentials(context.Context, *WatchSyncRefreshCredentialsRequest) (*WatchSyncCredentialResponse, error)
	GetAccount(context.Context, *WatchSyncGetAccountRequest) (*WatchSyncGetAccountResponse, error)
	ApplyEvents(context.Context, *WatchSyncApplyEventsRequest) (*WatchSyncApplyEventsResponse, error)
	ListRemoteState(context.Context, *WatchSyncListRemoteStateRequest) (*WatchSyncListRemoteStateResponse, error)
}

// UnimplementedWatchSyncProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchSyncProviderServer struct{}

func (UnimplementedWatchSyncProviderServer) InitAuthorize(context.Context, *WatchSyncInitAuthorizeRequest) (*WatchSyncInitAuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitAuthorize not implemented")
}
func (UnimplementedWatchSyncProviderServer) ExchangeCode(context.Context, *WatchSyncExchangeCodeRequest) (*WatchSyncCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeCode not implemented")
}
func (UnimplementedWatchSyncProviderServer) ExchangeAPIKey(context.Context, *WatchSyncExchangeAPIKeyRequest) (*WatchSyncCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAPIKey not implemented")
}
func (UnimplementedWatchSyncProviderServer) RefreshCredentials(context.Context, *WatchSyncRefreshCredentialsRequest) (*WatchSyncCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshCredentials not implemented")
}
func (UnimplementedWatchSyncProviderServer) GetAccount(context.Context, *WatchSyncGetAccountRequest) (*WatchSyncGetAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedWatchSyncProviderServer) ApplyEvents(context.Context, *WatchSyncApplyEventsRequest) (*WatchSyncApplyEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyEvents not implemented")
}
func (UnimplementedWatchSyncProviderServer) ListRemoteState(context.Context, *WatchSyncListRemoteStateRequest) (*WatchSyncListRemoteStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteState not implemented")
}
func (UnimplementedWatchSyncProviderServer) testEmbeddedByValue() {}

// UnsafeWatchSyncProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchSyncProviderServer will
// result in compilation errors.
type UnsafeWatchSyncProviderServer interface {
	mustEmbedUnimplementedWatchSyncProviderServer()
}

func RegisterWatchSyncProviderServer(s grpc.ServiceRegistrar, srv WatchSyncProviderServer) {
	// If the following call panics, it indicates UnimplementedWatchSyncProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchSyncProvider_ServiceDesc, srv)
}

func _WatchSyncProvider_InitAuthorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncInitAuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).InitAuthorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_InitAuthorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).InitAuthorize(ctx, req.(*WatchSyncInitAuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_ExchangeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncExchangeCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).ExchangeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_ExchangeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).ExchangeCode(ctx, req.(*WatchSyncExchangeCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_ExchangeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncExchangeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).ExchangeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_ExchangeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).ExchangeAPIKey(ctx, req.(*WatchSyncExchangeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_RefreshCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncRefreshCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).RefreshCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_RefreshCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).RefreshCredentials(ctx, req.(*WatchSyncRefreshCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncGetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).GetAccount(ctx, req.(*WatchSyncGetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_ApplyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncApplyEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).ApplyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_ApplyEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).ApplyEvents(ctx, req.(*WatchSyncApplyEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchSyncProvider_ListRemoteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSyncListRemoteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchSyncProviderServer).ListRemoteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchSyncProvider_ListRemoteState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchSyncProviderServer).ListRemoteState(ctx, req.(*WatchSyncListRemoteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchSyncProvider_ServiceDesc is the grpc.ServiceDesc for WatchSyncProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchSyncProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "silo.plugin.v1.WatchSyncProvider",
	HandlerType: (*WatchSyncProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAuthorize",
			Handler:    _WatchSyncProvider_InitAuthorize_Handler,
		},
		{
			MethodName: "ExchangeCode",
			Handler:    _WatchSyncProvider_ExchangeCode_Handler,
		},
		{
			MethodName: "ExchangeAPIKey",
			Handler:    _WatchSyncProvider_ExchangeAPIKey_Handler,
		},
		{
			MethodName: "RefreshCredentials",
			Handler:    _WatchSyncProvider_RefreshCredentials_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _WatchSyncProvider_GetAccount_Handler,
		},
		{
			MethodName: "ApplyEvents",
			Handler:    _WatchSyncProvider_ApplyEvents_Handler,
		},
		{
			MethodName: "ListRemoteState",
			Handler:    _WatchSyncProvider_ListRemoteState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "silo/plugin/v1/watch_sync_provider.proto",
}
